CREATE TABLE MASCOTAS (
ID_MASCOTA NUMBER  GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NOMBRE NVARCHAR2 (50),
RAZA NVARCHAR2 (50),
EDAD NUMBER,
RAZON_CITA NVARCHAR2 (100),
CLIENTE_ID NUMBER,
RESPONSABLE_ID NUMBER,
VETERINARIA_ID NUMBER
);


CREATE TABLE RESPONSABLES (
ID_RESPONSABLE NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NOMBRE NVARCHAR2 (100),
CONTACTO NUMBER,
VETERINARIA_ID NUMBER
);
