CREATE TABLE EMPLEADOS (
ID_EMPLEADO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NOMBRE NVARCHAR2 (100),
AREA_ID NUMBER
);



CREATE TABLE AREAS (
ID_AREA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NOMBRE NVARCHAR2 (100)
);

INSERT INTO AREAS (NOMBRE) VALUES (N'Administración');
INSERT INTO AREAS (NOMBRE) VALUES (N'Recursos Humanos');
INSERT INTO AREAS (NOMBRE) VALUES (N'Contabilidad');
INSERT INTO AREAS (NOMBRE) VALUES (N'Producción');
INSERT INTO AREAS (NOMBRE) VALUES (N'Logística');
INSERT INTO AREAS(NOMBRE) VALUES (N'Tecnología de la Información');
INSERT INTO AREAS (NOMBRE) VALUES (N'Marketing');
INSERT INTO AREAS (NOMBRE) VALUES (N'Ventas');


INSERT INTO EMPLEADOS (NOMBRE, AREA_ID) VALUES (N'Ana Martínez', 1); -- Administración
INSERT INTO EMPLEADOS (NOMBRE, AREA_ID) VALUES (N'Luis Gómez', 2);   -- Recursos Humanos
INSERT INTO EMPLEADOS (NOMBRE, AREA_ID) VALUES (N'Carla Ruiz', 3);   -- Contabilidad
INSERT INTO EMPLEADOS (NOMBRE, AREA_ID) VALUES (N'José Pérez', 4);   -- Producción
INSERT INTO EMPLEADOS (NOMBRE, AREA_ID) VALUES (N'Mariana Torres', 6); -- TI

SELECT * FROM EMPLEADOS;
SELECT * FROM AREAS;