CREATE TABLE USER_AU (
   USERNAME VARCHAR2(50),
     PASSWORD VARCHAR2(100),
    ROL VARCHAR2(50),
    CONSTRAINT USER_PK PRIMARY KEY (USERNAME)
);

INSERT INTO USER_AU VALUES ('eliam','12345', 'ROLE_ADMIN');
INSERT INTO USER_AU VALUES ('yan','123', 'ROLE_USER');
INSERT INTO USER_AU VALUES ('osva','12345', 'ROLE_ADMIN');

SELECT * FROM USER_AU;

DROP TABLE USER_AU;
COMMIT;

