CREATE TABLE ROLES (
    ID_ROL NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PRIVILEGIO VARCHAR2(50)
);

CREATE TABLE USUARIO (
    ID_USUARIO NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(50),
    APP VARCHAR2(50),
    APM VARCHAR2(50),
    SEXO CHAR(1) CHECK (SEXO IN ('M', 'F')),
    CORREO VARCHAR2(100),
    FECHA_NACIMIENTO DATE,
    FECHA_CREACION DATE DEFAULT SYSDATE,
    ROL_ID NUMBER(10)
);

COMMIT;

SELECT * FROM USUARIO;

-- Insertar datos en ROLES
INSERT INTO ROLES (PRIVILEGIO) VALUES ('ADMINISTRADOR');
INSERT INTO ROLES (PRIVILEGIO) VALUES ('EMPLEADO');
INSERT INTO ROLES (PRIVILEGIO) VALUES ('USUARIO');

-- Insertar datos en USUARIO
INSERT INTO USUARIO (
    NOMBRE, APP, APM, SEXO, CORREO, FECHA_NACIMIENTO, ROL_ID
) VALUES (
    'Carlos', 'Ramírez', 'Mendoza', 'M', 'carlos.ramirez@empresa.com', TO_DATE('1988-02-05', 'YYYY-MM-DD'), 3
);
INSERT INTO USUARIO (
    NOMBRE, APP, APM, SEXO, CORREO, FECHA_NACIMIENTO, ROL_ID
) VALUES (
    'Ana', 'Martínez', 'López', 'F', 'ana.martinez@empresa.com', TO_DATE('1992-11-15', 'YYYY-MM-DD'), 2
);

INSERT INTO USUARIO (
    NOMBRE, APP, APM, SEXO, CORREO, FECHA_NACIMIENTO, ROL_ID
) VALUES (
    'Luis', 'Gómez', 'Castillo', 'M', 'luis.gomez@empresa.com', TO_DATE('1985-06-30', 'YYYY-MM-DD'), 1
);

INSERT INTO USUARIO (
    NOMBRE, APP, APM, SEXO, CORREO, FECHA_NACIMIENTO, ROL_ID
) VALUES (
    'Sofía', 'Ramírez', 'Ortiz', 'F', 'sofia.ramirez@empresa.com', TO_DATE('1998-03-22', 'YYYY-MM-DD'), 3
);

INSERT INTO USUARIO (
    NOMBRE, APP, APM, SEXO, CORREO, FECHA_NACIMIENTO, ROL_ID
) VALUES (
    'Pedro', 'Vargas', 'Soto', 'M', 'pedro.vargas@empresa.com', TO_DATE('1990-09-05', 'YYYY-MM-DD'), 2
);


SELECT * FROM ROLES;
COMMIT;