CREATE TABLE VIDEOJUEGO(
ID_VIDEOJUEGO NUMBER,
NOMBRE NVARCHAR2(100),
CATEGORIA_ID NUMBER,
PRECIO NUMBER,
DESARROLLADORA_ID NUMBER,
CONSTRAINT VJ_PK PRIMARY KEY (ID_VIDEOJUEGO)

);

CREATE SEQUENCE S_ID_VJ
START WITH 1
MINVALUE 1
MAXVALUE 9999
NOCYCLE;
/

INSERT INTO VIDEOJUEGO VALUES(S_ID_VJ.NEXTVAL, 'FIFA 26', 1, 1400, 1);
INSERT INTO VIDEOJUEGO VALUES(S_ID_VJ.NEXTVAL, 'HALO REACH', 1, 1250 , 1);
INSERT INTO VIDEOJUEGO VALUES (S_ID_VJ.NEXTVAL, 'ZELDA SKYWARD SWORD ', 3, 1850, 2);
INSERT INTO VIDEOJUEGO VALUES (S_ID_VJ.NEXTVAL, 'THE LEGEND OF ZELDA', 2, 1850, 2);


--TABLA RESPALDO

CREATE TABLE RP_VIDEOJUEGO(
ID_VIDEOJUEGO NUMBER,
NOMBRE NVARCHAR2(100),
CATEGORIA_ID NUMBER,
PRECIO NUMBER,
DESARROLLADORA_ID NUMBER,
CONSTRAINT RP_VJ_PK PRIMARY KEY (ID_VIDEOJUEGO)

);


CREATE OR REPLACE PROCEDURE RP_RESPALDO_VJ
AS 
BEGIN
--ELIMINAR LO DEL RESPALDO
DELETE FROM RP_VIDEOJUEGO;

--RESPALDO
INSERT INTO RP_VIDEOJUEGO(ID_VIDEOJUEGO, NOMBRE, CATEGORIA_ID, PRECIO, DESARROLLADORA_ID)
SELECT ID_VIDEOJUEGO, NOMBRE, CATEGORIA_ID, PRECIO, DESARROLLADORA_ID FROM VIDEOJUEGO;
END RP_RESPALDO_VJ;

