----MI PRIMER API

CREATE TABLE BICICLETA (
ID_BICI NUMBER,
MARCA NVARCHAR2(100),
RODADA NUMBER,
COLOR NVARCHAR2(100),
VELOCIDADES NUMBER,
PRECIO NUMBER,
CONSTRAINT BICI_PK PRIMARY KEY (ID_BICI)
);

INSERT INTO BICICLETA VALUES (1,'LA MONTAÑA',2,'VERDE',6,1250); 
INSERT INTO BICICLETA VALUES (2,'TREK',28,'BLANCO',10,1580);
INSERT INTO BICICLETA VALUES (3, 'URBANA RÁPIDA', 3, 'AZUL', 18, 1799);

COMMIT;

SELECT * FROM BICICLETA;