------API CON PELICULA


CREATE TABLE PELICULA(
ID_PELI NUMBER,
NOMBRE NVARCHAR2(100),
DURACION NUMBER,
ESTRENO NVARCHAR2(100),
GENERO NVARCHAR2(100),
CONSTRAINT PELICULA_PK PRIMARY KEY (ID_PELI)
);


INSERT INTO PELICULA VALUES  (1,'DRACULA',2.30,'11 DE DICIEMBRE', 'TERROR');
INSERT INTO PELICULA VALUES  (2,'MARIO',1.30,'15 DE ENERO', 'ANIMACION');
INSERT INTO PELICULA VALUES  (3,'SONYC',3.30,'20 DE DICIEMBRE', 'ACCION');

COMMIT;

SELECT * FROM PELICULA;

