---TABLA COMPUTADORA
CREATE TABLE COMPUTADORA (
    ID_COMPUTADORA NUMBER,
    MARCA NVARCHAR2(100),
    MODELO NVARCHAR2(100),
    PROCESADOR NVARCHAR2(100),
    RAM NUMBER,
    PRECIO NUMBER,
    CONSTRAINT COMPU_PK PRIMARY KEY (ID_COMPUTADORA)
);



-----TABLA BITACORA 


CREATE TABLE BIT_COMPUTADORA (
    ID_BIT NUMBER,
    MARCA NVARCHAR2(100),
    MODELO NVARCHAR2(100),
    PROCESADOR NVARCHAR2(100),
    RAM NUMBER,
    PRECIO NUMBER,
    MOVIMIENTO NVARCHAR2(100),
    ID_COMPUTADORA NUMBER,
    MARCA_OLD NVARCHAR2(100),
    MODELO_OLD NVARCHAR2(100),
    PROCESADOR_OLD NVARCHAR2(100),
    RAM_OLD NVARCHAR2(100),
    PRECIO_OLD NVARCHAR2(100),
    FECHA_MOV DATE,
    USUARIO NVARCHAR2(100),
    CONSTRAINT BIT_COMPU_PK PRIMARY KEY(ID_BIT)
);


----TRIGGER PARA ACTUALIZACION 

CREATE OR REPLACE TRIGGER TR_U_COMPUTADORA
AFTER UPDATE ON COMPUTADORA
FOR EACH ROW
DECLARE
    LV_ID_BIT NUMBER;
    LV_FECHA DATE;
    LV_USUARIO NVARCHAR2(100);
BEGIN
    SELECT USER INTO LV_USUARIO FROM DUAL;
    SELECT SYSDATE INTO LV_FECHA FROM DUAL;
    SELECT NVL(MAX(ID_BIT), 0) + 1 INTO LV_ID_BIT FROM BIT_COMPUTADORA;

    INSERT INTO BIT_COMPUTADORA (
        ID_BIT, ID_COMPUTADORA, MARCA, MODELO, PROCESADOR, RAM, PRECIO,
        MARCA_OLD, MODELO_OLD, PROCESADOR_OLD, RAM_OLD, PRECIO_OLD,
        FECHA_MOV, USUARIO, MOVIMIENTO
    )
    VALUES ( -----CAMBIAR EL NEW 
        LV_ID_BIT, :NEW.ID_COMPUTADORA, :NEW.MARCA, :NEW.MODELO, :NEW.PROCESADOR, :NEW.RAM, :NEW.PRECIO,
        :OLD.MARCA, :OLD.MODELO, :OLD.PROCESADOR, TO_CHAR(:OLD.RAM), TO_CHAR(:OLD.PRECIO),
        LV_FECHA, LV_USUARIO, 'UPDATE'
    );
END TR_U_COMPUTADORA;
/

----TRIGGER PARA ELIMINACION 


CREATE OR REPLACE TRIGGER TR_D_COMPUTADORA
AFTER DELETE ON COMPUTADORA
FOR EACH ROW
DECLARE
    LV_ID_BIT NUMBER;
    LV_FECHA DATE;
    LV_USUARIO NVARCHAR2(100);
BEGIN
    SELECT USER INTO LV_USUARIO FROM DUAL;
    SELECT SYSDATE INTO LV_FECHA FROM DUAL;
    SELECT NVL(MAX(ID_BIT), 0) + 1 INTO LV_ID_BIT FROM BIT_COMPUTADORA; -----SI LA TABLA ESTA VACIA (ES DECIR, MAX(ID_BIT) ES  NULL), LO REEMPLAZA POR UN  0.

    INSERT INTO BIT_COMPUTADORA (
        ID_BIT, ID_COMPUTADORA, MARCA, MODELO, PROCESADOR, RAM, PRECIO,
        MARCA_OLD, MODELO_OLD, PROCESADOR_OLD, RAM_OLD, PRECIO_OLD,
        FECHA_MOV, USUARIO, MOVIMIENTO
    )
    VALUES (
        LV_ID_BIT, :OLD.ID_COMPUTADORA, NULL, NULL, NULL, NULL, NULL,
        :OLD.MARCA, :OLD.MODELO, :OLD.PROCESADOR, TO_CHAR(:OLD.RAM), TO_CHAR(:OLD.PRECIO),
        LV_FECHA, LV_USUARIO, 'DELETE'
    );
END TR_D_COMPUTADORA;
/



INSERT INTO COMPUTADORA VALUES (1, 'LENOVO', 'NUEVO MODELO','INTEL I5',8,8800);
INSERT INTO COMPUTADORA VALUES (2, 'ACER', 'NUEVO MODELO','INTEL I8',4,5800);
INSERT INTO COMPUTADORA VALUES (3, 'PC GAMING ', 'NUEVO MODELO','INTEL I9',3,6800);
INSERT INTO COMPUTADORA VALUES (4, 'HAWAI', 'NUEVO MODELO','INTEL I3',21,4800);


COMMIT;



-- VER USUARIO CONECTADO 
SELECT USER FROM DUAL;

--VER LA FECHA ACTUAL 
SELECT SYSDATE FROM DUAL;

-- VER TODOS LOS REGISTROS 
SELECT * FROM COMPUTADORA;
SELECT * FROM BIT_COMPUTADORA;

-----ELIMINAR 

DELETE FROM COMPUTADORA
WHERE ID_COMPUTADORA = 4;


---VERIFICAR EN BITACORA EL MOVIMIENTO DELETE PARA VER SI SI SE ELIMINO 
SELECT * FROM BIT_COMPUTADORA
WHERE MOVIMIENTO = 'DELETE'
ORDER BY FECHA_MOV DESC;

----PARA ACTUALIZAR 

UPDATE COMPUTADORA
SET MARCA = 'PC MEDIO GAMING',
    PRECIO = 100800,
    MODELO = 'BIEN BIEN VIEJO',
     PROCESADOR = 'INTEL i10',
     RAM = 30
    
WHERE ID_COMPUTADORA = 4;


-- VER LA TABLA PRINCIPAL ACTUALIZADA 
SELECT * FROM COMPUTADORA
WHERE ID_COMPUTADORA = 4;

-- VER EL REGISTRO EN LA BITACORA ACTUALIZADA
SELECT * FROM BIT_COMPUTADORA
WHERE MOVIMIENTO = 'UPDATE'
ORDER BY FECHA_MOV DESC;


COMMIT;