CREATE OR REPLACE TRIGGER TR_VALIDAR_EDAD_ALUMNO
BEFORE INSERT ON ALUMNO
FOR EACH ROW
BEGIN
    IF :NEW.EDAD < 18 THEN
        RAISE_APPLICATION_ERROR(-20002, ' ERROR: No se permite registrar alumnos menores de 18 años.');
    END IF;
END;
/



----PRUEBA INSERTAR ALUMNO MENOR 

INSERT INTO ALUMNO(ID_ALUMNO, NOMBRE, APELLIDO, EDAD)
VALUES (301, 'Pedro', 'Juárez', 17);



-----PRUEBA INSERTAR ALUMNO MAYOR DE 18 AÑOS 

INSERT INTO ALUMNO(ID_ALUMNO, NOMBRE, APELLIDO, EDAD)
VALUES (302, 'Laura', 'Díaz', 20);


SELECT * FROM ALUMNO;


DELETE FROM ALUMNO
WHERE ID_ALUMNO = 301;