---CURSORES : ES UNA ESTRUCTURA QUE PERMITE RECORRER Y PROCESAR FILAS DE UN CONJUNTO DE RESULTADOS DE UNA CONSULTA DE MANERA PROGRAMATICA EN UN BLOQUE 
---PODEMOS UTILIZAR LOS CURSORES PARA REALIZAR OPERACIONES COMO LECTURA, ACTUALIZACION Y ELIMINACION EN UN TABLA 


SELECT * FROM LIBRO;



CREATE OR REPLACE PROCEDURE PR_DETALLE_LIBRO

IS 
--- DECLARAMOS EL CURSOR 


CURSOR LIBRO_INFO IS 
SELECT NOMBRE,
CASE GENERO
    WHEN 1 THEN 'DRAMA'
    WHEN 2 THEN 'TERROR'
    WHEN 3 THEN 'HISTORIA'
    WHEN 4 THEN 'CIENCIA FICCION'
    WHEN 5 THEN 'POESIA'
    ELSE 'SIN GENERO'
    
    END AS GENERO_LIBRO, PRECIO 
    FROM LIBRO;
    ---VARIABLE LOCALES 
    
    LV_NOMBRE NVARCHAR2(100);
    LV_GENERO NVARCHAR2(100);
    LV_PRECIO LIBRO.PRECIO%TYPE; ---- % ES LO MISMO QUE NUMBER, SIRVE PARA REFERECNIAR EN CAS ODE NO SABER QUE TIPO ES NUMBER, NVARCHAR2 ETC
    
    BEGIN 
    ---ABRIR EL CURSOR 
    
    OPEN LIBRO_INFO;
    
    ---RECUPERO LOS DATOS DEL CURSOR 
    
    LOOP
    --ALMACENARLO EN LAS VARIABLES LOCALES
    
    FETCH LIBRO_INFO INTO LV_NOMBRE, LV_GENERO, LV_PRECIO;
    
    --CONDICION PARA CERRAR EL CICLO
    
    EXIT WHEN LIBRO_INFO%NOTFOUND;
    
    ----MOSTRAR EN LA CONSOLA LO QUE TIENEN LAS VARIABLES 
    
    
    DBMS_OUTPUT.PUT_LINE('LIBRO: ' || LV_NOMBRE || ' DEL GENERO ' || LV_GENERO || ' CUESTA $' || LV_PRECIO);
    END LOOP;
    
    ---CIERRO EL CURSOR 
    
    
    CLOSE LIBRO_INFO;
    
    
    END PR_DETALLE_LIBRO;
    /
    
    BEGIN 
    PR_DETALLE_LIBRO;
    END;
    /
