CREATE OR REPLACE FUNCTION OBTENER_DOCENTE(

P_ID_MATERIA IN NUMBER
) RETURN VARCHAR IS 
V_NOMBRE_DOCENTE VARCHAR2(100);
BEGIN 
SELECT D.NOMBRE_DOCENTE
INTO V_NOMBRE_DOCENTE 
FROM MATERIA M
JOIN DOCENTE D ON M.DOCENTE_ID = D.ID_DOCENTE
WHERE M.ID_MATERIA = P_ID_MATERIA;

RETURN V_NOMBRE_DOCENTE;
EXCEPTION
WHEN NO_DATA_FOUND THEN
RETURN 'NO SE ENCONTRO DOCENTE';
WHEN OTHERS THEN 
RETURN ' ERROR AL OBTENER EL DOCENTE';
END ;
/

-------VERIFICAMOS SI APARECE EL ID QUE SOLICITAMOS 
SELECT OBTENER_DOCENTE(101) FROM DUAL; 


DESC MATERIA;