CREATE TABLE AUDITORIA_ALUMNO (
    ID_AUDITORIA     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FECHA_AUDITORIA  DATE,
    NUM_ALUMNOS      NUMBER,
    OPERACION        VARCHAR2(20)
);


CREATE OR REPLACE TRIGGER TR_AUDITORIA_INS_ALUMNO
AFTER INSERT ON ALUMNO
DECLARE
    V_NUM_ALUMNOS NUMBER;
BEGIN
    -- Obtener el número de filas insertadas en la sentencia
    V_NUM_ALUMNOS := SQL%ROWCOUNT;

    INSERT INTO AUDITORIA_ALUMNO (FECHA_AUDITORIA, NUM_ALUMNOS, OPERACION)
    VALUES (SYSDATE, V_NUM_ALUMNOS, 'INSERT');
END;
/

INSERT INTO ALUMNO(ID_ALUMNO, NOMBRE, APELLIDO, EDAD)
VALUES (501, 'Carlos', 'Sánchez', 22);

INSERT INTO ALUMNO(ID_ALUMNO, NOMBRE, APELLIDO, EDAD)
VALUES (502, 'Marta', 'Díaz', 23);

INSERT INTO ALUMNO(ID_ALUMNO, NOMBRE, APELLIDO, EDAD)
VALUES (503, 'Marta', 'Díaz', 23);

INSERT INTO ALUMNO(ID_ALUMNO, NOMBRE, APELLIDO, EDAD)
VALUES (504, 'Marta', 'Díaz', 23);

SELECT * FROM AUDITORIA_ALUMNO;