CREATE OR REPLACE PROCEDURE MOSTRAR_DETALLE_MATERIA(P_ID_MATERIA IN NUMBER) IS
    V_TOTAL NUMBER;

    CURSOR C_ALUMNOS IS
        SELECT A.NOMBRE, A.APELLIDO
        FROM ALUMNO A
        JOIN ALUMNO_MATERIA AM ON A.ID_ALUMNO = AM.ALUMNO_ID
        WHERE AM.MATERIA_ID = P_ID_MATERIA;

BEGIN
    -- Contar total
    SELECT COUNT(*)
    INTO V_TOTAL
    FROM ALUMNO_MATERIA
    WHERE MATERIA_ID = P_ID_MATERIA;

    DBMS_OUTPUT.PUT_LINE('TOTAL DE ALUMNOS INSCRITOS: ' || V_TOTAL);

    -- Mostrar nombres
    FOR ALUM IN C_ALUMNOS LOOP
        DBMS_OUTPUT.PUT_LINE('Alumno: ' || ALUM.NOMBRE || ' ' || ALUM.APELLIDO);
    END LOOP;
END;
/
  
CREATE OR REPLACE PROCEDURE REGISTRAR_NUEVO_ALUMNO(
    P_ID_ALUMNO IN NUMBER,
    P_NOMBRE IN VARCHAR2,
    P_APELLIDO IN VARCHAR2,
    P_CARRERA_ID IN NUMBER,
    P_EDAD IN NUMBER
) IS
BEGIN
    INSERT INTO ALUMNO (ID_ALUMNO, NOMBRE, APELLIDO, CARRERA_ID, EDAD)
    VALUES (P_ID_ALUMNO, P_NOMBRE, P_APELLIDO, P_CARRERA_ID, P_EDAD);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Alumno registrado: ' || P_NOMBRE || ' ' || P_APELLIDO);
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE('Error: El ID de alumno ya existe.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inesperado: ' || SQLERRM);
END;
/






-- Mostrar detalle de alumnos inscritos en materia con ID = 1
BEGIN
    MOSTRAR_DETALLE_MATERIA(1);
END;
/

-- Registrar un alumno nuevo
BEGIN
    REGISTRAR_NUEVO_ALUMNO(133, 'Ana', 'Gómez', 2, 19);
END;
/


----INSCRIBIR NUEVO ALUMNO
INSERT INTO ALUMNO_MATERIA (ALUMNO_ID, MATERIA_ID)
VALUES (20, 1);

COMMIT;
SELECT ID_ALUMNO FROM ALUMNO ORDER BY ID_ALUMNO;