----EJERCICIO: CREAR 2 FUNCIONES UNA QUE CALCULE EL AREA DE UN CIRCULO Y OTRO EL AREA DE UN TRIANGULO.


---FUNCION: AREA DE UN CIRCULO


CREATE OR REPLACE FUNCTION AREA_CIRCULO (RADIO IN NUMBER)
RETURN NUMBER
IS 
AREA NUMBER;

BEGIN
AREA := 3.1416 * RADIO * RADIO;
RETURN AREA;
END;
/

---FUNCION AREA DE UN TRIANGULO 

CREATE OR REPLACE FUNCTION AREA_TRIANGULO (BASE IN NUMBER, ALTURA IN NUMBER)
RETURN NUMBER
IS 
AREA NUMBER;
BEGIN 
AREA := (BASE * ALTURA) / 2;
RETURN AREA;
END;
/





DECLARE

RESULTADO_CIRCULO NUMBER;
RESULTADO_TRIANGULO NUMBER;

BEGIN 
--- CALCULAR AREA DE UN CIRCULO CON RADIO 5 

RESULTADO_CIRCULO := AREA_CIRCULO(5);
DBMS_OUTPUT.PUT_LINE('AREA DEL CIRCULO CON RADIO DE 5 : ' || RESULTADO_CIRCULO);



RESULTADO_TRIANGULO := AREA_TRIANGULO (10, 4);
DBMS_OUTPUT.PUT_LINE('AREA DEL TRIANGULO CON (BASE DE 10, ALTURA 4):' || RESULTADO_TRIANGULO);

END;
/

