SET SERVEROUTPUT ON;
DECLARE
    
    P_ID_MATERIA NUMBER := 1;

    -- Variables del cursor
    V_NOMBRE ALUMNO.NOMBRE%TYPE;
    V_APELLIDO ALUMNO.APELLIDO%TYPE;
    V_CARRERA CARRERA.NOMBRE_CARRERA%TYPE;

    -- CURSOR CON JOIN EN LA TABLA CARRERA 
    CURSOR CURSOR_ALUMNOS IS
        SELECT A.NOMBRE, A.APELLIDO, C.NOMBRE_CARRERA
        FROM ALUMNO A
        JOIN CARRERA C ON A.CARRERA_ID = C.ID_CARRERA
        JOIN ALUMNO_MATERIA AM ON A.ID_ALUMNO = AM.ALUMNO_ID
        WHERE AM.MATERIA_ID = P_ID_MATERIA;

BEGIN
    OPEN CURSOR_ALUMNOS;
    LOOP
        FETCH CURSOR_ALUMNOS INTO V_NOMBRE, V_APELLIDO, V_CARRERA;
        EXIT WHEN CURSOR_ALUMNOS%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('Alumno: ' || V_NOMBRE || ' ' || V_APELLIDO || ' | Carrera: ' || V_CARRERA);
    END LOOP;
    CLOSE CURSOR_ALUMNOS;
END;
/







---CONSULTA NOMBRE Y NOMBRE CARRERAS 
SELECT 
    A.NOMBRE || ' ' || A.APELLIDO AS NOMBRE_ALUMNO,
    C.NOMBRE_CARRERA
FROM 
    ALUMNO A
JOIN 
    CARRERA C ON A.CARRERA_ID = C.ID_CARRERA;
    
    ------CONSULTA NOMBRE Y IDS
    
    SELECT 
    A.NOMBRE || ' ' || A.APELLIDO AS NOMBRE_ALUMNO,
    A.CARRERA_ID AS ID_CARRERA
FROM 
    ALUMNO A
ORDER BY 
    A.NOMBRE;
    
    
    
SELECT DISTINCT CARRERA_ID FROM ALUMNO ORDER BY CARRERA_ID;

SELECT ID_CARRERA, NOMBRE_CARRERA FROM CARRERA ORDER BY ID_CARRERA;