
SELECT * FROM MATERIA;

CREATE TABLE MATERIA (
ID_MATERIA NUMBER,
NOMBRE NVARCHAR2 (100),
NIVEL NUMBER,
DOCENTE NUMBER,
CREDITOS NUMBER,
CONSTRAINT MATERIA_PK PRIMARY KEY (ID_MATERIA)
);
--DOCENTE: 1 ALEJANDRO, 2 AXEL, 3 BRENDA, 4 MARTHA, 5, FERNANDO, 6 GERARDO
INSERT INTO MATERIA VALUES(1, 'ANATOMIA', 1, 3, 25);
INSERT INTO MATERIA VALUES(2, 'BASE DE DATOS', 2, NULL, 30);
INSERT INTO MATERIA VALUES(3, 'QUIMICA', 1, 5, 30);
INSERT INTO MATERIA VALUES(4, 'PROGRAMACION', 1, NULL, 25);
INSERT INTO MATERIA VALUES(5, 'HISTORIA', 2, 3, 30);
INSERT INTO MATERIA VALUES(6, 'DESARROLLO WEB', 1, 1, 20);
INSERT INTO MATERIA VALUES(7, 'BASES DE DATOS', 3, 2, 28);
INSERT INTO MATERIA VALUES(8, 'MATEMATICAS', 2, NULL, 32);
INSERT INTO MATERIA VALUES(9, 'SISTEMAS OPERATIVOS', 1, 3, 26);
INSERT INTO MATERIA VALUES(10, 'BASES DE DATOS', 3, 2, 28);
INSERT INTO MATERIA VALUES(11, 'MATEMATICAS', 2, NULL, 32);
INSERT INTO MATERIA VALUES(12, 'SISTEMAS OPERATIVOS', 1, 3, 26);
INSERT INTO MATERIA VALUES(13, 'LOGICA', 5, NULL, 20);
INSERT INTO MATERIA VALUES(14, 'TOPICOS', 6, 4, 15);
INSERT INTO MATERIA VALUES(15, 'ECUACIONES', 3, 6, 20);

-------1. MOSTRAR LOS REGISTROS DE LOS ALUMNOS CON SUS MATERIAS Y LOS CASES PARA DOCENTE Y CARRERA.
---FALTA MOSTRAR MATERIAS 
SELECT 
    A.ID_ALUMNO,
    A.NOMBRE || ' ' || A.APELLIDO AS NOMBRE_COMPLETO,
    A.EDAD,

    CASE A.CARRERA
        WHEN 1 THEN 'SISTEMAS'
        WHEN 2 THEN 'MEDICINA'
        WHEN 3 THEN 'DERECHO'
        WHEN 4 THEN 'ADMINISTRACION'
        WHEN 5 THEN 'MATEMATICAS'
        ELSE 'NO REGISTRADA'
    END AS CARRERA,

    M.NOMBRE AS MATERIA,

    CASE M.DOCENTE
        WHEN 1 THEN 'ALEJANDRO'
        WHEN 2 THEN 'AXEL'
        WHEN 3 THEN 'BRENDA'
        WHEN 4 THEN 'MARTHA'
        WHEN 5 THEN 'FERNANDO'
        WHEN 6 THEN 'GERARDO'
        ELSE 'NO ASIGNADO'
    END AS DOCENTE

FROM ALUMNO A
LEFT JOIN MATERIA M ON A.MATERIA_ID = M.ID_MATERIA
ORDER BY A.ID_ALUMNO;


-----2. CONTAR CUANTOS ALUMNOS TENGO POR MATERIA.
SELECT 
M.NOMBRE AS MATERIA,
COUNT (A.ID_ALUMNO) AS TOTAL_ALUMNOS
FROM MATERIA M
LEFT JOIN ALUMNO A ON M.ID_MATERIA = A.MATERIA_ID
GROUP BY M.NOMBRE
ORDER BY TOTAL_ALUMNOS DESC;

------3. MOSTRAR A LA O LAS MATERIAS CON EL MAYOR NUMERO DE CREDITOS Y AGREGARLE LA PALABRA "CREDITOS", con su CASE.
SELECT 
    M.NOMBRE AS MATERIA,

    -- Mostrar créditos con la palabra "CREDITOS"
    CASE
        WHEN M.CREDITOS IS NOT NULL THEN TO_CHAR(M.CREDITOS) || ' CREDITOS'
        ELSE 'SIN INFORMACION'
    END AS TOTAL_CREDITOS,

    -- Mostrar el nombre del docente
    CASE M.DOCENTE
        WHEN 1 THEN 'ALEJANDRO'
        WHEN 2 THEN 'AXEL'
        WHEN 3 THEN 'BRENDA'
        WHEN 4 THEN 'MARTHA'
        WHEN 5 THEN 'FERNANDO'
        WHEN 6 THEN 'GERARDO'
        ELSE 'NO ASIGNADO'
    END AS DOCENTE

FROM MATERIA M
WHERE M.CREDITOS = (
    SELECT MAX(CREDITOS) FROM MATERIA
);

-----4. MOSTRAR AL DOCENTE(NOMBRE) Y EL NUMERO DE MATERIAS QUE IMPARTE

SELECT
CASE DOCENTE 
 WHEN 1 THEN 'ALEJANDRO'
    WHEN 2 THEN 'AXEL'
    WHEN 3 THEN 'BRENDA'
    WHEN 4 THEN 'MARTHA'
    WHEN 5 THEN 'FERNANDO'
    WHEN 6 THEN 'GERARDO'
    ELSE  'NO ASIGNADO'
    END AS NOMBRE_DOCENTE,
    COUNT (*) AS NUM_MATERIAS
    FROM MATERIA 
    WHERE DOCENTE IS NOT NULL
    GROUP BY DOCENTE 
    ORDER BY NUM_MATERIAS DESC;
    
    ----5. MOSTRAR AL DOCENTE(NOMBRE) QUE IMPARTE MAS MATERIAS QUE LOS DEMAS
   SELECT 
   CASE DOCENTE 
 WHEN 1 THEN 'ALEJANDRO'
    WHEN 2 THEN 'AXEL'
    WHEN 3 THEN 'BRENDA'
    WHEN 4 THEN 'MARTHA'
    WHEN 5 THEN 'FERNANDO'
    WHEN 6 THEN 'GERARDO'
    ELSE  'NO ASIGNADO'
    END AS NOMBRE_DOCENTE,
    COUNT (*) AS NUM_MATERIAS
    FROM MATERIA
    WHERE DOCENTE IS NOT NULL
    GROUP BY DOCENTE ----AGRUPA POR DOCENTE Y CUENTA CAUNTAS MATERIAS TIENE CADA UNO 
   HAVING COUNT (*) = ( -------HAVING FILTRA PARA MOSTRAR SOLO AL DOCENTE CON ESE NUMERO MAXIMO.
   SELECT MAX(CANTIDAD)
   FROM (
   SELECT DOCENTE, COUNT (*) AS CANTIDAD 
   FROM MATERIA  
   WHERE DOCENTE IS NOT NULL
   GROUP BY DOCENTE )
   );


-----6. ORDENA LAS MATERIAS DE MAYOR A MENOR POR SU NOMBRE Y DESPUES POR CREDITOS.(CASE)


SELECT 
NOMBRE AS MATERIA,
CASE 
WHEN CREDITOS IS NOT NULL THEN TO_CHAR(CREDITOS) ||' CREDITOS ' 
ELSE 'SIN DATOS'
END AS CREDITOS_FORMATO
FROM MATERIA
ORDER BY NOMBRE DESC, CREDITOS DESC; ---ORDER BY ordena primero por el nombre de la materia en orden descendente (Z-A), y si hay nombres repetidos, por los créditos de mayor a menor. 

-------7 MOSTRAR LAS MATERIAS QUE NO SEAN TOMADAS POR NINGUN ALUMNO. (CASE DOCENTE)
SELECT 
M.NOMBRE AS MATERIA, ---Usar AS MATERIA cambia el nombre de la columna en el resultado, no afecta los datos, solo los hace más legibles al usuario o reporte final.
---- CASE PARA MOSTRAR EL NOMBRE DEL DOCENTE 
CASE M.DOCENTE
WHEN 1 THEN 'ALEJANDRO'
WHEN 2 THEN 'AXEL'
WHEN 3 THEN 'BRENDA'
WHEN 4 THEN 'MARTHA'
WHEN 5 THEN 'FERNANDO'
WHEN 6 THEN 'GERARDO'
ELSE 'NO ASIGNADO'
END AS NOMBRE_DOCENTE

FROM MATERIA M
WHERE M.ID_MATERIA NOT IN (
SELECT DISTINCT MATERIA_ID ---SELECT DISTINCT Te da una sola vez cada valor distinto de MATERIA_ID (sin repeticiones).
FROM ALUMNO 
WHERE MATERIA_ID IS NOT NULL ---Filtra los resultados para que solo muestre los que sí tienen materia asignada (es decir, que no estén en blanco o vacíos).
)
ORDER BY M.NOMBRE;

----8 MOSTRAR LA CARRERA O LAS CARRERAS CON EL MAYOR NUMERO DE ALUMNOS (NOMBRE)


SELECT 
CASE CARRERA 

WHEN 1 THEN 'SISTEMAS'
WHEN 2 THEN 'MEDICINA'
WHEN 3 THEN 'DERECHO'
WHEN 4 THEN 'ADMINISTRACION'
WHEN 5 THEN 'MATEMATICAS'
ELSE 'NO REGISTRADA'

END AS NOMBRE_CARRERA,

COUNT(*) AS TOTAL_ALUMNOS
FROM  ALUMNO
WHERE CARRERA IS NOT NULL
GROUP BY CARRERA 
HAVING COUNT (*) = ( ---HAVING se utiliza junto con GROUP BY para filtrar los resultados agrupados, después de haber contado, sumado, promediado, etc.
SELECT MAX(CANTIDAD)
FROM (
SELECT CARRERA, COUNT(*) AS CANTIDAD
FROM ALUMNO
WHERE CARRERA IS NOT NULL
GROUP BY CARRERA
)
);
-----9 MOSTRAR LAS MATERIAS POR NIVEL DE MENOR A MAYOR.
SELECT 
NOMBRE AS MATERIA,
NIVEL
FROM MATERIA
ORDER BY NIVEL ASC;

-----10 MOSTRAR A LOS ALUMNOS QUE NO ESTAN INSCRITOS EN NINGUNA MATERIA. CASE (CARRERA)
----Muestra los alumnos cuyo MATERIA_ID está vacío (NULL), 
---lo que significa que no están inscritos en ninguna materia. 
---/ Concatena NOMBRE + APELLIDO como NOMBRE_COMPLETO. / Usa CASE para convertir el número de carrera a su nombre real.
---/Si CARRERA también es NULL, mostrará 'NO REGISTRADA'.
SELECT 
ID_ALUMNO,
NOMBRE || ' ' || APELLIDO AS NOMBRE_COMPLETO,
EDAD,
CASE CARRERA
WHEN 1 THEN 'SISTEMAS'
WHEN 2 THEN 'MEDICINA'
WHEN 3 THEN 'DERECHO'
WHEN 4 THEN 'ADMINISTRACION'
WHEN 5 THEN 'MATEMATICAS'
ELSE 'NO ASIGNADO'
END AS NOMBRE_CARRERA
FROM ALUMNO 
WHERE MATERIA_ID IS NULL;

----11 CONTAR CUANTOS ALUMNOS ESTAN INSCRITOS EN LA MATERIA DE ANATOMIA Y MOSTRAR AL DOCENTE QUE LA IMPARTE (CASE, CARRERA)
SELECT 
M.NOMBRE AS MATERIA,

CASE M.DOCENTE

WHEN 1 THEN 'ALEJANDRO'
WHEN 2 THEN 'AXEL'
WHEN 3 THEN 'BRENDA'
WHEN 4 THEN 'MARTHA'
WHEN 5 THEN 'GERARDO'
ELSE 'NO ASIGNADO'
END AS NOMBRE_DOCENTE,

CASE A.CARRERA
WHEN 1 THEN 'SISTEMAS'
WHEN 2 THEN 'MEDICINA'
WHEN 2 THEN 'DERECHO'
WHEN 4 THEN 'ADMINISTRACION'
WHEN 5 THEN 'MATEMATICAS'
ELSE 'NO REGISTRADA'
END AS CARRERA_ALUMNO,

COUNT (A.ID_ALUMNO) AS TOTAL_ALUMNOS

FROM MATERIA M 
LEFT JOIN ALUMNO A ON M.ID_MATERIA = A.MATERIA_ID
WHERE M.NOMBRE = 'ANATOMIA'
GROUP BY M.NOMBRE, M.DOCENTE, A.CARRERA;


----12 MOSTRAR A LOS ALUMNOS QUE CURSAN MATERIAS CON 30 O MAS CREDITOS  Y ORDENALOS POR APELLIDO DE MENOR A MAYOR Y POR NOMBRE.

SELECT

A.ID_ALUMNO,
A.NOMBRE,
A.APELLIDO,
A.EDAD,
M.NOMBRE AS MATERIA,
M.CREDITOS
FROM ALUMNO A
JOIN MATERIA M ON A.MATERIA_ID = M.ID_MATERIA
WHERE M.CREDITOS >= 30
ORDER BY A.APELLIDO ASC, A.NOMBRE ASC;
------13 MOSTRAR EL DETALLE DE CADA ALUMNO CON LOS DATOS DE LA MATERIA.


SELECT
A.ID_ALUMNO,
A.NOMBRE,
A.APELLIDO,
A.EDAD,

CASE A.CARRERA
-----EL DETALLE SE REFIERE A UNA SOLA COLUMNA 
WHEN 1 THEN 'SISTEMAS'
WHEN 2 THEN 'MEDICINA'
WHEN 3 THEN 'DERECHO'
WHEN 4 THEN 'ADMINISTRACION'
WHEN 5 THEN 'MATEMATICAS'
ELSE 'NO HAY MATERIA'
END AS CARRERA,



M.ID_MATERIA,
M.NOMBRE AS NOMBRE_MATERIA,
M.NIVEL,


CASE M.DOCENTE
WHEN 1 THEN 'ALEJANDRO'
WHEN 2 THEN 'AXEL'
WHEN 3 THEN 'BRENDA'
WHEN 4 THEN 'MARTHA'
WHEN 5 THEN 'FERNANDO'
ELSE 'NO HAY DOCENTE'
END AS DOCENTE,

M.CREDITOS
FROM ALUMNO A
LEFT JOIN MATERIA M ON A.MATERIA_ID = M.ID_MATERIA
ORDER BY A.ID_ALUMNO; ---Se usa LEFT JOIN para incluir alumnos que no tengan materia asignada (su materia aparecerá como NULL).



COMMIT;

SELECT * FROM ALUMNO;
CREATE TABLE ALUMNO (
ID_ALUMNO NUMBER,
NOMBRE NVARCHAR2 (100),
APELLIDO NVARCHAR2 (100),
EDAD NUMBER,
CARRERA NUMBER,
MATERIA_ID NUMBER,

CONSTRAINT ALUMNO_PK PRIMARY KEY (ID_ALUMNO),
CONSTRAINT ALUMNO_FK FOREIGN KEY (MATERIA_ID) REFERENCES MATERIA (ID_MATERIA)
);
--CARRERA: 1 SISTEMAS, 2 MEDICINA, 3 DERECHO, 4 ADMINSTRACION, 5 MATEMATICAS



INSERT INTO ALUMNO VALUES(1, 'DIEGO', 'ROJAS', 23, NULL, NULL);
INSERT INTO ALUMNO VALUES(2, 'MARIA', 'HERNANDEZ', 19, 1, 7);
INSERT INTO ALUMNO VALUES(3, 'FERNANDA', 'ROSAS', 20, 4, 1);
INSERT INTO ALUMNO VALUES(4, 'VICTOR', 'SANCHEZ SANCHEZ', 25, 2, 14);
INSERT INTO ALUMNO VALUES(5, 'FRANCISCO', 'MACHORRO CHAVEZ', 22, 2, 12);
INSERT INTO ALUMNO VALUES(6, 'DULCE', 'PELAEZ DIAS', 21, 5, 3);
INSERT INTO ALUMNO VALUES(7, 'ALICIA', 'REYES', 18, 1, 2);
INSERT INTO ALUMNO VALUES(8, 'JORGE', 'MENDEZ', 24, 3, 5);
INSERT INTO ALUMNO VALUES(9, 'KARLA', 'TORRES', 20, 4, 9);
INSERT INTO ALUMNO VALUES(10, 'SANTIAGO', 'JIMENEZ JIMENEZ', 19, 5, 15);
INSERT INTO ALUMNO VALUES(11, 'BEJAMIN', 'ALVAREZ LORENZO', 22, 1, 14);
INSERT INTO ALUMNO VALUES(12, 'ABRAHAM', 'PEREZ ARIAS', 26, NULL, 13);
INSERT INTO ALUMNO VALUES(13, 'VALERIA', 'MARTINEZ LOPEZ', 20, 3, 12);
INSERT INTO ALUMNO VALUES(14, 'ANDREA', 'GARCIA REYES', 18, 4, NULL);
INSERT INTO ALUMNO VALUES(15, 'MATEO', 'RODRIGUEZ HERNANDEZ', 21, 2, 11);