CREATE OR REPLACE PROCEDURE REGISTRAR_ALUMNO (
    P_ID_ALUMNO   IN ALUMNO.ID_ALUMNO%TYPE,
    P_NOMBRE      IN ALUMNO.NOMBRE%TYPE,
    P_APELLIDO    IN ALUMNO.APELLIDO%TYPE,
    P_EDAD        IN ALUMNO.EDAD%TYPE,
    P_ID_MATERIA  IN MATERIA.ID_MATERIA%TYPE
)
IS
    V_EXISTE_MATERIA NUMBER;
BEGIN
    -- Verifica si la materia existe
    SELECT COUNT(*) INTO V_EXISTE_MATERIA
    FROM MATERIA
    WHERE ID_MATERIA = P_ID_MATERIA;

    IF V_EXISTE_MATERIA = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'ERROR; LA MATERIA NO EXISTE NO SE PUEDE REGISTRAR AL ALUMNO.');
    END IF;

    -- Inserta al alumno
    INSERT INTO ALUMNO(ID_ALUMNO, NOMBRE, APELLIDO, EDAD)
    VALUES (P_ID_ALUMNO, P_NOMBRE, P_APELLIDO, P_EDAD);

    -- Relaciona al alumno con la materia
    INSERT INTO ALUMNO_MATERIA(ALUMNO_ID, MATERIA_ID)
    VALUES (P_ID_ALUMNO, P_ID_MATERIA);

    DBMS_OUTPUT.PUT_LINE('EL ALUMNO SE HA REGISTRADO CORRECTAMENTE.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('❗ Error: ' || SQLERRM);
END;
/

SELECT * FROM MATERIA;

INSERT INTO MATERIA (ID_MATERIA, NOMBRE_MATERIA)
VALUES (4, 'Bases de Datos');


BEGIN
    REGISTRAR_ALUMNO(101, 'Ana', 'Ramírez', 22, 5);
END;
/

SELECT * FROM ALUMNO;
SELECT * FROM ALUMNO_MATERIA;