CREATE TABLE AUTOMOVIL (
ID NUMBER PRIMARY KEY,
MARCA VARCHAR2(50),
SUBMARCA VARCHAR2(50),
MODELO NUMBER,
COLOR VARCHAR2(30),
PRECIO NUMBER,
VERSION VARCHAR2(50),
CONSTRAINT AUTOMOVIL_PK PRIMARY KEY (ID_AUTOMOVIL)
);


INSERT INTO AUTOMOVIL VALUES(1, 'VOLKSWAGEN', 'JETA A6', 2025, 'NEGRO', 385000, 'CONFORT LINE');
INSERT INTO AUTOMOVIL VALUES(2, 'TOYOTA', 'COROLLA', 2023, 'PLATEADO', 320000, NULL);
INSERT INTO AUTOMOVIL VALUES(3, 'HONDA', 'CIVIC', 2022, 'AZUL', 350000, 'EX');
INSERT INTO AUTOMOVIL VALUES(4, 'TOYOTA', 'CAMRY', 2023, 'PLATEADO', 35000, 'SEDÁN');
INSERT INTO AUTOMOVIL VALUES(5, 'FORD', 'MUSTANG', 2022, 'AZUL', 50000, 'DEPORTIVO');
INSERT INTO AUTOMOVIL VALUES(6, 'AUDI', 'F6', 2024, 'PLATEADO', 980000, 'DYNAMO');
INSERT INTO AUTOMOVIL VALUES(7, 'BMW', 'SERIE 3', 2024, 'ROJO', 780000, 'M SPORT');
INSERT INTO AUTOMOVIL VALUES(8, 'NISSAN', 'SENTRA', 2023, 'BLANCO', 330000, 'ADVANCE');
INSERT INTO AUTOMOVIL VALUES(9, 'KIA', 'FORTE', 2022, 'GRIS', 310000, 'GT LINE');
INSERT INTO AUTOMOVIL VALUES(10, 'CHEVROLET', 'ONIX', 2004, 'ROJO', 285000, 'LTZ');
INSERT INTO AUTOMOVIL VALUES(11, 'MAZDA', '3 SEDÁN', 2023, 'NEGRO', 410000, 'I TOURING');
INSERT INTO AUTOMOVIL VALUES(12, 'HYUNDAI', 'ELANTRA', 2022, 'BLANCO', 360000, 'GLS PREMIUM');
INSERT INTO AUTOMOVIL VALUES (13, 'SEAT', 'IBIZA', 2023, 'VERDE', 280000, 'FR');
INSERT INTO AUTOMOVIL VALUES (14, 'TESLA', 'MODEL 3', 2025, 'GRIS', 900000, 'PERFORMANCE');
INSERT INTO AUTOMOVIL VALUES (15, 'RENAULT', 'KWID', 2022, 'BLANCO', 200000, 'ZEN');

COMMIT;
SELECT * FROM AUTOMOVIL;

-- 1.AUTOS ORDENADOS POR PRECIO DE MAYOR A MENOR, CON FORMATO DE MONEDA
SELECT ID, MARCA, SUBMARCA, MODELO, COLOR, TO_CHAR(PRECIO, '$999,999,999.00') AS PRECIO_FORMATO, VERSION
FROM AUTOMOVIL ORDER BY PRECIO DESC;

-- 2. PROMEDIO DE PRECIO DE AUTOS CUYA SUBMARCA CONTIENE LA LETRA 'E'
SELECT TO_CHAR(AVG(PRECIO), '$999,999,999.00') AS PROMEDIO_PRECIO FROM AUTOMOVIL WHERE SUBMARCA LIKE '%E%';

-- 3. Autos con precio mayor o igual a 400,000, submarca en minúsculas, formato de precio
SELECT ID, MARCA, LOWER(SUBMARCA) AS SUBMARCA_MINUSCULAS, MODELO,COLOR, TO_CHAR(PRECIO, '$999,999,999.00') AS PRECIO_FORMATO, VERSION FROM AUTOMOVIL WHERE PRECIO >= 400000;

-- 4. AUTOS CON VERSION NO NULO Y PRECIO > 350,000, ORDENADOS DE MENOR A MAYOR PRECIO
SELECT ID, MARCA, SUBMARCA, MODELO, COLOR,  TO_CHAR(PRECIO, '$999,999,999.00') AS PRECIO_FORMATO,  VERSION FROM AUTOMOVIL WHERE VERSION IS NOT NULL AND PRECIO > 350000
ORDER BY PRECIO ASC;

-- 5. AUTOS CON PRECIO ENTRE 450,000 Y 600,000
SELECT  ID, MARCA, SUBMARCA, MODELO, COLOR, TO_CHAR(PRECIO, '$999,999,999.00') AS PRECIO_FORMATO, VERSION
FROM AUTOMOVIL WHERE PRECIO BETWEEN 450000 AND 600000;

-- 6. AUTOS DE COLOR AZUL, CON FORMATO DE PRECIO Y PALABRA "PESOS"
SELECT ID,MARCA,SUBMARCA,MODELO,COLOR,TO_CHAR(PRECIO, '$999,999,999.00') || ' PESOS' AS PRECIO_FORMATO,VERSION
FROM AUTOMOVIL WHERE COLOR = 'AZUL';

-- 7. CONTAR CUANTOS HAY POR CADA MARCA
SELECT 
  MARCA,COUNT(*) AS TOTAL_AUTOS
FROM AUTOMOVIL
GROUP BY MARCA;

-- 8. MOSTRAR EL AUTO CON MAYOR PRECIO CON FORMATO
SELECT ID,MARCA,SUBMARCA, MODELO, COLOR, TO_CHAR(PRECIO, '$999,999,999.00') AS PRECIO_FORMATO, VERSION
FROM AUTOMOVIL WHERE PRECIO = (SELECT MAX(PRECIO) FROM AUTOMOVIL);

-- 9.MOSTRAR EL AUTO MAS ANTIGUO, AGREGAR "AÑO" AL MODELO Y FORMATO AL PRECIO
SELECT  ID, MARCA, SUBMARCA, 'AÑO ' || MODELO AS MODELO, COLOR, TO_CHAR(PRECIO, '$999,999,999.00') AS PRECIO_FORMATO, VERSION
FROM AUTOMOVIL WHERE MODELO = (SELECT MIN(MODELO) FROM AUTOMOVIL);

-- 10.ACTUALIZAR EL PRECIO DE AUTOS MODELO 2024, INCREMENTANDO UN 10%

SELECT * FROM AUTOMOVIL WHERE MODELO = 2024;
UPDATE AUTOMOVIL
SET PRECIO = PRECIO * 1.10
WHERE MODELO = 2024;
COMMIT;
////SIRVE PARA GUARDAR LOS CAMBIOS
ROLLBACK;
/////SIRVE PARA REINICIAR LOS VALORES

-- CONSULTA PARA VERIFICAR LOS CAMBIOS
SELECT  ID, MARCA, SUBMARCA, MODELO, COLOR, TO_CHAR(PRECIO, '$999,999,999.00') AS PRECIO_FORMATADO FROM AUTOMOVIL
WHERE MODELO = 2024;

-- 11. MOSTRAR AUTOS ORDENADOS POR MARCA ASCENDENTE Y PRECIO DESCENDENTE
SELECT  ID  MARCA,  SUBMARCA,  MODELO,  COLOR,  TO_CHAR(PRECIO, '$999,999,999.00') AS PRECIO_FORMATO,  VERSION
FROM AUTOMOVIL ORDER BY MARCA ASC, PRECIO DESC;

-- 12. DESGLOSAR DETALLE COMPLETO DEL AUTO EN UNA SOLA COLUMNA
SELECT 
  'ID: ' || ID || 
  ', MARCA: ' || MARCA || 
  ', SUBMARCA: ' || SUBMARCA || 
  ', MODELO: ' || MODELO || 
  ', COLOR: ' || COLOR || 
  ', PRECIO: ' || TO_CHAR(PRECIO, '$999,999,999.00') || 
  ', VERSION: ' || NVL(VERSION, 'SIN VERSION') AS DETALLE_AUTO
FROM AUTOMOVIL;
////NVL SIRVE PARA REEMPLAZAR VALORES NULOS (NULL) POR VALORES QUE TU ELIJAS EJEMPLO: (VALOR,REEMPLAZO)
/////LA NUMERACION QUE APARECE EN EL RESULTADO NO FORMA PARTE DEL RESULTADO ES PARTE DE SQL Y NO SE PUEDE QUITAR