---DESHABILITAR LOS TRIGGERS CON BIT_COMPUTADORA

ALTER TRIGGER TR_D_COMPUTADORA DISABLE;


CREATE OR REPLACE TRIGGER TR_MULTIPLE_COMPUTADORA
AFTER INSERT OR UPDATE OR DELETE 
ON COMPUTADORA
FOR EACH ROW 
DECLARE
LV_BIT_COMPUTADORA NUMBER;
LV_USUARIO NVARCHAR2(100);
LV_FECHA DATE;

BEGIN 
---GARDAR EN LAS VARIABLES 

SELECT USER, SYSDATE, S_ID_BIT.NEXTVAL INTO LV_USUARIO, LV_FECHA, LV_BIT_COMPUTADORA FROM DUAL;

----CONDICIONALES DE TRIGGER

IF INSERTING THEN 
INSERT INTO BIT_COMPUTADORA(ID_BIT, ID_COMPUTADORA,PROCESADOR, MARCA, MODELO, RAM, PRECIO, MARCA_OLD, MODELO_OLD, PROCESADOR_OLD, RAM_OLD, PRECIO_OLD, 
FECHA_MOV,USUARIO, MOVIMIENTO)
VALUES (LV_BIT_COMPUTADORA, : NEW.ID_COMPUTADORA, :NEW.MARCA, :NEW.MODELO, :NEW.PROCESADOR, :NEW.RAM, :NEW.PRECIO,NULL,NULL,NULL,0,0,
LV_FECHA, LV_USUARIO,'INSERT');


ELSIF UPDATING THEN 
INSERT INTO BIT_COMPUTADORA(ID_BIT, ID_COMPUTADORA,PROCESADOR, MARCA, MODELO, RAM, PRECIO, MARCA_OLD, MODELO_OLD, PROCESADOR_OLD, RAM_OLD, PRECIO_OLD, 
FECHA_MOV,USUARIO, MOVIMIENTO)
VALUES (LV_BIT_COMPUTADORA, :OLD.ID_COMPUTADORA, :NEW.PROCESADOR, :NEW.MARCA, :NEW.MODELO, :NEW.RAM, :NEW.PRECIO, :OLD.MARCA, :OLD.MODELO,
:OLD.PROCESADOR, :OLD.RAM, :OLD.PRECIO, LV_FECHA, LV_USUARIO, 'UPDATE');

ELSIF DELETING THEN
INSERT INTO BIT_COMPUTADORA (ID_BIT, ID_COMPUTADORA,PROCESADOR, MARCA, MODELO, RAM, PRECIO, MARCA_OLD, MODELO_OLD, PROCESADOR_OLD, RAM_OLD, PRECIO_OLD, 
FECHA_MOV,USUARIO, MOVIMIENTO)
VALUES (LV_BIT_COMPUTADORA, :OLD.ID_COMPUTADORA,NULL,NULL,NULL,0,0, :OLD.MARCA, :OLD.MODELO, :OLD.PROCESADOR, :OLD.RAM, :OLD.PRECIO,
LV_FECHA, LV_USUARIO, 'DELETE');

END IF ;


END TR_MULTIPLE_COMPUTADORA;
/


SELECT * FROM BIT_COMPUTADORA;
SELECT * FROM COMPUTADORA;

INSERT INTO COMPUTADORA VALUES (1,'APPLE NUEVO','APPLE','MAC 223', 16,3400);
INSERT INTO COMPUTADORA VALUES (2,'APPLE NUEVO','APPLE','MAC 223', 16,3400);

COMMIT;

UPDATE COMPUTADORA SET RAM = 32 WHERE ID_COMPUTADORA IN (2,3);

DELETE FROM COMPUTADORA WHERE ID_COMPUTADORA = 5;
DELETE FROM COMPUTADORA;


