CREATE TABLE LIBRO2 (
ID_LIBRO2 NUMBER,
NOMBRE NVARCHAR2(100),
AUTOR NVARCHAR2(100),
GENERO NVARCHAR2(100),
PRECIO NUMBER,
EDITORIAL NVARCHAR2(100),
CONSTRAINT LIBRO2_PK PRIMARY KEY (ID_LIBRO2)
);





CREATE TABLE BIT_LIBRO (
  ID_BIT NUMBER,
  
  -- Valores nuevos
  NOMBRE_NEW NVARCHAR2(100),
  AUTOR_NEW NVARCHAR2(100),
  GENERO_NEW NVARCHAR2(100),
  PRECIO_NEW NUMBER,
  EDITORIAL_NEW NVARCHAR2(100),
  MOVIMIENTO NVARCHAR2(100),
  ID_LIBRO NUMBER,

  -- Valores antiguos
  NOMBRE_OLD NVARCHAR2(100),
  AUTOR_OLD NVARCHAR2(100),
  GENERO_OLD NVARCHAR2(100),
  PRECIO_OLD NUMBER,
  EDITORIAL_OLD NVARCHAR2(100),
  ID_LIBRO_OLD NUMBER,
  
  -- Campos de control
  FECHA_MOV DATE,
  USUARIO NVARCHAR2(100),

  CONSTRAINT BIT_LIBRO2_PK PRIMARY KEY(ID_BIT)
);



CREATE OR REPLACE TRIGGER TR_MULTIPLE_LIBRO2
AFTER INSERT OR UPDATE OR DELETE 
ON LIBRO2
FOR EACH ROW 
DECLARE
  LV_BIT_LIBRO2 NUMBER;
  LV_USUARIO NVARCHAR2(100);
  LV_FECHA DATE;
BEGIN 
  SELECT USER, SYSDATE, S_ID_BIT.NEXTVAL 
  INTO LV_USUARIO, LV_FECHA, LV_BIT_LIBRO2 
  FROM DUAL;

  IF INSERTING THEN 
    INSERT INTO BIT_LIBRO(
      ID_BIT, ID_LIBRO, NOMBRE_NEW, AUTOR_NEW, GENERO_NEW, PRECIO_NEW, EDITORIAL_NEW,
      NOMBRE_OLD, AUTOR_OLD, GENERO_OLD, PRECIO_OLD, EDITORIAL_OLD, 
      FECHA_MOV, USUARIO, MOVIMIENTO
    )
    VALUES (
      LV_BIT_LIBRO2, :NEW.ID_LIBRO2, :NEW.NOMBRE, :NEW.AUTOR, :NEW.GENERO, :NEW.PRECIO, :NEW.EDITORIAL,
      NULL, NULL, NULL, NULL, NULL,
      LV_FECHA, LV_USUARIO, 'INSERT'
    );

  ELSIF UPDATING THEN 
    INSERT INTO BIT_LIBRO(
      ID_BIT, ID_LIBRO, NOMBRE_NEW, AUTOR_NEW, GENERO_NEW, PRECIO_NEW, EDITORIAL_NEW,
      NOMBRE_OLD, AUTOR_OLD, GENERO_OLD, PRECIO_OLD, EDITORIAL_OLD, 
      FECHA_MOV, USUARIO, MOVIMIENTO
    )
    VALUES (
      LV_BIT_LIBRO2, :OLD.ID_LIBRO2, :NEW.NOMBRE, :NEW.AUTOR, :NEW.GENERO, :NEW.PRECIO, :NEW.EDITORIAL,
      :OLD.NOMBRE, :OLD.AUTOR, :OLD.GENERO, :OLD.PRECIO, :OLD.EDITORIAL,
      LV_FECHA, LV_USUARIO, 'UPDATE'
    );

  ELSIF DELETING THEN
    INSERT INTO BIT_LIBRO(
      ID_BIT, ID_LIBRO, NOMBRE_NEW, AUTOR_NEW, GENERO_NEW, PRECIO_NEW, EDITORIAL_NEW,
      NOMBRE_OLD, AUTOR_OLD, GENERO_OLD, PRECIO_OLD, EDITORIAL_OLD, 
      FECHA_MOV, USUARIO, MOVIMIENTO
    )
    VALUES (
      LV_BIT_LIBRO2, :OLD.ID_LIBRO2, NULL, NULL, NULL, NULL, NULL,
      :OLD.NOMBRE, :OLD.AUTOR, :OLD.GENERO, :OLD.PRECIO, :OLD.EDITORIAL,
      LV_FECHA, LV_USUARIO, 'DELETE'
    );
  END IF;

END TR_MULTIPLE_LIBRO2;
/


SELECT * FROM BIT_LIBRO;
SELECT * FROM LIBRO2;

INSERT INTO LIBRO2 VALUES (1,'MINECRAFT GUIA','MOJANG','FICCION', 16,'MOJANG');
INSERT INTO LIBRO2 VALUES (2,'WIGUETTA','VEGETTA Y WILLY','FICCION', 25,'MINECRAFT');
INSERT INTO LIBRO2 VALUES (3,'EL CHAVO','ENRIQUE CEGOVIANO','COMEDIA', 35,'TELEVISA');
INSERT INTO LIBRO2 VALUES (4,'WARZONE','ELVENADO97','DISPAROS', 55,'ACTIVISON');

COMMIT;

UPDATE LIBRO2 SET NOMBRE = 'WARZONETE' WHERE ID_LIBRO2 IN (4);

DELETE FROM LIBRO2  WHERE ID_LIBRO2 = 1;



