----VISTAS O VIEWS SON OBJETOS QUE SE TOMAN COMO ALTERNATIVAS PARA MOSTRAR DATOS DE VARIAS TABLAS COMO UNA SOLA 
----ES COMO UNA TABLA VIRTUAL QUE ALMACENA UNA CONSULTA, YA QUE ES UNA TABLA LOGICA BASADA EN OTRAS TABLAS O VISTAS , EN SI MISMA
--NO CONTIENE DATOS ES UNA VENTANA A TRAVES DE LA CUAL SE OBSERVAN LOS MISMOS DATOS
--- ES UNA ALTERNATIVA UTIL PARA RESTRINGIR EL ACCESO A LA BASE DE DATOS Y ELABORAR COMSULTAS COMPLEJAS DE MANERAFACIL Y TENERLAS ALMACENADAS


SELECT * FROM PADRE;
SELECT * FROM HIJO;


---CREAR UNA VISTA QUE NOS MUESTRE EL HIJO CON SU PADRE


CREATE OR REPLACE VIEW V_PADRE_HIJO

AS 
SELECT H.NOMBRE, H.APELLIDO, H.HOBBIE, NVL(P.NOMBRE, 'SIN REGISTRO') AS NOMBRE_PADRE, NVL (P.TRABAJO, 'SIN TRABAJO')AS TRABAJO_PADRE
FROM HIJO H LEFT JOIN PADRE P ON H.PADRE_ID = P.ID_PADRE;

--EJECUTAR VISTA

SELECT * FROM V_PADRE_HIJO;