---BLOQUS PL/SQL

--SINTAXIS
--DECLARE
--VARIABLES, CONSTANTES O CURSORES
---BEGIN 
---INSTRUCCIONES A EJECUTAR
----END;
---/

BEGIN 
DBMS_OUTPUT.PUT_LINE('HOLA MUNDO DESDE BLOQUE PL/SQL');
END;
/


-----ESTRUCTURAS DE CONDICION, CICLOS Y VARIABLES
DECLARE
LV_ITERADOR NUMBER := 0;

BEGIN 

LOOP 
DBMS_OUTPUT.PUT_LINE('VALOR DEL ITERADOR: ' || LV_ITERADOR);
LV_ITERADOR := LV_ITERADOR + 1;
EXIT WHEN LV_ITERADOR = 11;
END LOOP;
END;
/


------CICLO FOR

BEGIN
FOR i IN 1..20
LOOP
DBMS_OUTPUT.PUT_LINE('VALOR DE i: ' || i);
END LOOP;
END;
/

---CLICLO WHILE

DECLARE 
LV_ITERADOR NUMBER := 0;
BEGIN 
WHILE LV_ITERADOR <= 20
LOOP
DBMS_OUTPUT.PUT_LINE('VALOR DEL ITERADOR: ' || LV-ITERADOR);
LV_ITERADOR := LV_ITERADOR + 1;
END LOOP;
END;
/

--USO DEL BOLEAN --IF
DECLARE 
LV_VALIDADOR BOOLEAN := FAlSE;
BEGIN 
FOR i IN 1..20
LOOP
DBMS_OUTPUT.PUT_LINE('VALOR DE i: ' || i);
IF i = 15 THEN
LV_VALIDADOR := TRUE;
END IF ;
EXIT WHEN LV_VALIDADOR;
END LOOP;
END;
/
---EJERCICIO : REALIZAR UN BLOQUE PL/SQL QUE MUESTRE SU NOMBRE COMPLETO, CARRERA Y LUGAR DE RESIDENCIA, DE IGUAL MANERA 
---MOSTRAR LAS TABLAS DE MULTIPLICAR DE 1 AL 10

DECLARE
----DATOS PERSONALES 
V_NOMBRE VARCHAR2(100) := 'Miguel Eliam Rosas Vega';
V_CARRERA VARCHAR2(100) := 'Ingeniero en sistemas ';
V_RESIDENCIA VARCHAR2(100) := 'Orizaba Veracruz';

----VARIABLES PARA LA TABLA DE MULTIPLICAR 

i NUMBER;
j NUMBER;

BEGIN 

-----MOSTRAR LOS DATOS PERSONALES 

DBMS_OUTPUT.PUT_LINE('NOMBRE COMPLETO   :' || V_NOMBRE);
DBMS_OUTPUT.PUT_LINE('CARRERA    :'  ||  V_CARRERA);
DBMS_OUTPUT.PUT_LINE('RESIDENCIA    :' || V_RESIDENCIA);
DBMS_OUTPUT.PUT_LINE('.................................');
DBMS_OUTPUT.PUT_LINE('TABLAS DE MULTIPLICAR DEL 1 AL 10 ');


FOR i IN 1..10 
LOOP
DBMS_OUTPUT.PUT_LINE(' TABLA DEL : ' || i || '---' );
FOR j IN 1..10 
LOOP
DBMS_OUTPUT.PUT_LINE( i || ' x ' || j || ' = ' || (i * j));
END LOOP;
DBMS_OUTPUT.PUT_LINE(''); ---- ESPACIO ENTRE TABLAS 
END LOOP;
END;
/