---JOINS. SE UTILIZAN DOS O MAS ENTIDADES EN FUNCION DE UNA CONDICION
--INNER: COMBINACION DE DOS O MAS ENTIDADES DONDE EXISTE UNA COINCIDENCIA Y SOLO DEVUELVEN LOS REGISTROS QUE CUMPLAN LA COINCIDENCIA. (FK)
--LEFT: DEVUELVE LAS COINCIDENCIAS (INNER) ADEMAS DE LOS REGISTROS DE LA ENTIDAD DERECHA
--RIGTH DEVUELVE LAS COINCIDENCIAS (INNER) Y LOS REGISTROS DE LA ENTIDAD IZQUIERDA
--FULL: DEVUELVE TODAS LAS FILAS DE AMBAS ENTIDADES
--CROSS: COMBINA CADA FILA DE LA PRIMERA TABLA CON TODAS LAS DE LA SEGUNDA TABLA GENERANDO UN PRODUCTO CARTESIANO


---TABLA PADRE

CREATE TABLE PADRE (

ID_PADRE NUMBER,
NOMBRE NVARCHAR2 (100),
APELLIDO NVARCHAR2 (100),
EDAD NUMBER,
TRABAJO NVARCHAR2 (100),
CONSTRAINT PADRE_PK PRIMARY KEY (ID_PADRE)
);

INSERT INTO PADRE VALUES(1, 'CARLOS', 'VARGAS', 39, 'CHOFER');
INSERT INTO PADRE VALUES(2, 'DANIELA', 'LOPEZ', 37, 'SUPERVISOR');
INSERT INTO PADRE VALUES(3, 'MARIO', 'GUTIERREZ', 45, 'INGENIERO');
INSERT INTO PADRE VALUES(4, 'VERONICA', 'CASTRO', 41, 'ENFERMERA');
INSERT INTO PADRE VALUES(5, 'MARIO', 'HERNÁNDEZ', 45, 'MECÁNICO');
INSERT INTO PADRE VALUES(6, 'LAURA', 'RAMÍREZ', 42, 'ENFERMERA');
INSERT INTO PADRE VALUES(7, 'SANTIAGO', 'BALCAZAR', 28, 'RESIDENTE');
INSERT INTO PADRE VALUES(8, 'MARITZA', 'GARCIA', 32, 'POLICIA');

COMMIT;

---TABLA HIJO

CREATE TABLE HIJO (
ID_HIJO NUMBER,
NOMBRE NVARCHAR2 (100),
APELLIDO NVARCHAR2 (100),
EDAD NUMBER,
HOBBIE NVARCHAR2 (100),
PADRE_ID NUMBER,
CONSTRAINT HIJO_PK PRIMARY KEY (ID_HIJO),
CONSTRAINT HIJO_FK FOREIGN KEY (PADRE_ID) REFERENCES PADRE(ID_PADRE)
);

INSERT INTO HIJO VALUES(1, 'ROSA', 'GARCIA', 12, 'BALLET', 8);
INSERT INTO HIJO VALUES(2, 'JUAN', 'ROBLES', 19, 'CANTAR', NULL);
INSERT INTO HIJO VALUES(3, 'LUISA', 'PEREZ', 15, 'PINTURA', 8);
INSERT INTO HIJO VALUES(4, 'DIEGO', 'SANCHEZ', 10, 'FUTBOL', 6);
INSERT INTO HIJO VALUES(5, 'ANDRÉS', 'PÉREZ', 13, 'KARATE', 2);
INSERT INTO HIJO VALUES(6, 'RENATA', 'GUZMÁN', 9, 'GIMNASIA', 4);
INSERT INTO HIJO VALUES(7, 'BERENICE', 'JIMENEZ', 30, 'VOLEIBOL', 8);
INSERT INTO HIJO VALUES(8, 'MIRIAM', 'HERNANDEZ', 28, 'CORRER', 7);


SELECT * FROM PADRE;
SELECT * FROM HIJO;

--INTER JOIN
SELECT * FROM HIJO H INNER JOIN PADRE P 
ON H.PADRE_ID = P.ID_PADRE;

--LEFT JOIN

SELECT * FROM HIJO H LEFT JOIN PADRE P 
ON H.PADRE_ID = P.ID_PADRE;
----LEFT JOIN CON CONDICION 
SELECT * FROM HIJO H LEFT JOIN PADRE P 
ON H.PADRE_ID = ID_PADRE
WHERE P.ID_PADRE IS NULL;

---RIGH JOIN 
SELECT * FROM HIJO H RIGHT JOIN PADRE P 
ON H.PADRE_ID = P.ID_PADRE;
----RIGHT JOIN CON CONDICION 
SELECT * FROM HIJO H RIGHT JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE
WHERE H.PADRE_ID IS NULL;

---FULL JOIN 
SELECT * FROM HIJO H FULL JOIN PADRE P 
ON H.PADRE_ID = P.ID_PADRE;

---FULL JOIN CON CONDICION
SELECT * FROM HIJO H FULL JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE
WHERE H.PADRE_ID IS NULL OR P.ID_PADRE IS NULL;