CREATE OR REPLACE VIEW VISTA_ALUMNOS_MATERIAS AS 
SELECT 
    A.NOMBRE || ' ' || A.APELLIDO AS NOMBRE_ALUMNO,
    A.CARRERA_ID AS CARRERA, -- Puedes unir con tabla CARRERA si existe
    M.NOMBRE_MATERIA,
    D.NOMBRE_DOCENTE
FROM 
    ALUMNO A
JOIN 
    ALUMNO_MATERIA AM ON A.ID_ALUMNO = AM.ALUMNO_ID
JOIN 
    MATERIA M ON AM.MATERIA_ID = M.ID_MATERIA
JOIN 
    DOCENTE D ON M.DOCENTE_ID = D.ID_DOCENTE
ORDER BY 
    A.NOMBRE;
    
    ----MOSTRAT VIEW
    SELECT * FROM VISTA_ALUMNOS_MATERIAS;

DESC ALUMNO;
DESC ALUMNO_MATERIA;
DESC MATERIA;
DESC DOCENTE;
DESC CARRERA;


SELECT * FROM CARRERA;