----SECUENCIA: ES UN OBJETO DE BASE DE DATOS QUE GENERA NUMERO SECUENCIALES UNICOS DE FORMA AUTOMATICA
---GENERA PK.

CREATE SEQUENCE S_ID_BIT
START WITH 2
INCREMENT BY 1
MAXVALUE 9999
NOCYCLE;
/



--COMO SE MANDA  A TRAER LA SECUENCIA?
SELECT S_ID_BIT.NEXTVAL FROM DUAL;

--COMO BORRO LA SECUENCIA?
---CON DROP SEQUENCE S_ID_BIT;


SELECT * FROM BIT_COMPUTADORA;