----CONTR A LAS PERSONAS DE CADA PROFESION 


SELECT  PROFESION, COUNT (ID_PERSONA) AS TOTAL FROM PERSONA WHERE PROFESION IS NOT NULL GROUP BY PROFESION;
// SUMA DE LAS EDADES DE LAS PERSONAS 

SELECT SUM(EDAD) AS SUMA_EDADES FROM PERSONA;

---ENCONTRAR LA EDAD MAXIMA 

SELECT MAX (EDAD) AS EDAD_MAXIMA FROM PERSONA;

------EDAD MINIMA

SELECT MIN (EDAD ) AS EDAD_MINIMA FROM PERSONA;

----PROMEDIO DE EDAD 
SELECT AVG(EDAD) AS PROMEDIO FROM PERSONA;

----REDONDEAR
SELECT ROUND (AVG(EDAD), 1) AS REDONDEO FROM PERSONA;

-----FORMATO CHAR A UN NUMERO


SELECT TO_CHAR(AVG(EDAD), 'FM999,999.999') AS FORMATO FROM PERSONA;


--CONCAT

SELECT CONCAT(CONCAT(CONCAT('LA PERSONA ', ID_PERSONA), ' '), NOMBRE) AS ENUNCIADO FROM PERSONA;

---PIPE||
SELECT NOMBRE || ' ' || APELLIDO || ' TIENE ' || EDAD || 'AÑOS Y SE DEDICA A ' || PROFESION AS ENUNCIADO FROM PERSONA;

----SUBCONSULTAS

SELECT * FROM PERSONA WHERE EDAD = 
(
SELECT MAX (EDAD) FROM PERSONA
);


-----EDAD MINIMA 
SELECT * FROM PERSONA WHERE EDAD = 
(
SELECT MIN (EDAD) FROM PERSONA
);

---PARA CONVERTIR A MAYUSCULAS 
SELECT UPPER (NOMBRE) AS MAYUSCULAS FROM PERSONAS;
SELECT LOWER (NOMBRE) AS MINUSCULAS FROM PERSONAS;




