CREATE TABLE BIT_COMPUTADORA_SET(
ID_BIT_SET NUMBER,
USUARIO NVARCHAR2(100),
FECHA_MOV DATE,
MOVIMIENTO NVARCHAR2(100),
CONSTRAINT BIT_SET_PK PRIMARY KEY (ID_BIT_SET)
);


CREATE SEQUENCE S_BIT_SEN
START WITH 1
MAXVALUE 9999
NOCYCLE
/

CREATE OR REPLACE TRIGGER TR_I_U_D_COMPUTADORA
AFTER INSERT OR UPDATE OR DELETE 
ON COMPUTADORA
DECLARE 
LV_ID_BIT NUMBER;
LV_USUARIO NVARCHAR2 (100);
LV_FECHA DATE;
LV_MOV NVARCHAR2(10);
BEGIN 

SELECT USER, SYSDATE,S_BIT_SEN.NEXTVAL INTO LV_USUARIO, LV_FECHA, LV_ID_BIT FROM DUAL;

IF  INSERTING THEN 
LV_MOV := 'INSERT';

ELSIF UPDATING THEN
LV_MOV := 'UPDATE';

END IF ;

INSERT INTO BIT_COMPUTADORA_SET(ID_BIT_SET, USUARIO, MOVIMIENTO, FECHA_MOV)
VALUES (LV_ID_BIT, USER, LV_MOV, LV_FECHA);
END TR_I_U_D_COMPUTADORA;
/


INSERT INTO COMPUTADORA VALUES(3, 'ASUS', 'ASUS 2', 'INTEL I7', 8, 8600);
INSERT INTO COMPUTADORA VALUES(4, 'LENOVO', 'CURRY ', 'INTEL I9', 8, 1000);
INSERT INTO COMPUTADORA VALUES(5, 'MSI', 'GS66 Stealth', 'Intel Core i9', 32, 45000);


COMMIT;

UPDATE COMPUTADORA SET RAM = 32 WHERE ID_COMPUTADORA IN (1,2,3);
DELETE FROM COMPUTADORA;

SELECT * FROM COMPUTADORA;



