--SENTENCIA CASE ---- LA SENTENCIA CASE ES UNA CONDICIONAL PARA REALIZAR EVALUACIONES A DIFERENTES CONDICIONES 
--SINTAXIS
--CASE
--WHEN CONDICION_1 THEN RESULTADO:1
--WHEN CONDICION_N THEN RESULTADO_N
--ELSE RESULTADO_ PREDETERMINADO
--END;

CREATE TABLE LIBRO(
ID_LIBRO NUMBER,
NOMBRE NVARCHAR2(100),
AUTOR NVARCHAR2(100),
GENERO NUMBER, --1 DRAMA, 2 TERROR, 3 HISTORIA, 4 CIENCIA, 5 FICCION, 6 POESIA
PRECIO NUMBER, 
EDITORIAL NVARCHAR2(100),
CONSTRAINT LIBRO_PK PRIMARY KEY(ID_LIBRO)
);

INSERT INTO LIBRO VALUES(1, 'DRACULA', 'BRAM STOKER', 2, 279, 'LOS PINOS');
INSERT INTO LIBRO VALUES(2, 'CABALLO DE TROYA', NULL, NULL, 670, 'ALLENDE');
INSERT INTO LIBRO VALUES(3, '1984', 'GEORGE ORWELL', 1, 328, 'CENTRO');
INSERT INTO LIBRO VALUES(4, 'EL PRINCIPITO', 'ANTOINE' , 3, 96, 'NORTE');
INSERT INTO LIBRO VALUES(5, 'CIEN AÑOS DE SOLEDAD', 'GABRIEL GARCÍA MÁRQUEZ', 1, 417, 'SUR');
INSERT INTO LIBRO VALUES(6, 'LA SOMBRA DEL VIENTO', 'CARLOS RUIZ ZAFÓN', 2, 565, 'ESTE');

COMMIT;

 --1 DRAMA, 2 TERROR, 3 HISTORIA, 4 CIENCIA, 5 FICCION, 6 POESIA
 
 SELECT * FROM LIBRO;
 SELECT ID_LIBRO, NOMBRE, AUTOR,
 CASE GENERO
 WHEN 1 THEN 'DRAMA'
 WHEN 2 THEN 'TERROR'
 WHEN 3 THEN 'HISTORIA'
 WHEN 4 THEN 'CIENCIA FICCION'
 WHEN 5 THEN 'POESIA'
 ELSE 'SIN GENERO'
 END AS GENEROS, PRECIO, EDITORIAL
 FROM LIBRO;
 
 SELECT NOMBRE, AUTOR, 
 CASE
 WHEN PRECIO <= 500 THEN 'EL LIBRO ES BARATO: ' || TO_CHAR(PRECIO, 'FM$999.00')
 WHEN PRECIO > 500 THEN 'EL LIBRO ES CARO: ' || TO_CHAR(PRECIO, 'FM$9,99.00')
 ELSE 'SIN PRECIO'
 END AS COSTO FROM LIBRO;





