---TRIGGER SIMPLE SE ACTIVA EN AUTOMATICO ANTES CIERTOS EVENTOS 

/* 
CREATE OR REPLACE TIPO_DE_BLOQUE NOMBRE
TIEMPO EN EL QUE SE VA A ACTIVAR (AFTER, BEFORE, INSTEAD OF )

EVENTO(INSERT, UPDATE, DELETE)
ON OBJETO

TIPO_TRIGGER
DECLARE
-- VARIABLES, CONSTANTE O CURSORES

BEGIN 

--CODIGO

END NOMBRE;
/

*/

CREATE TABLE COMPUTADORA(
ID_COMPUTADORA NUMBER,
MARCA NVARCHAR2 (100),
MODELO NVARCHAR2 (100),
PROCESADOR NVARCHAR2 (100),
RAM NUMBER,
PRECIO NUMBER,
CONSTRAINT COMPU_PK PRIMARY KEY (ID_COMPUTADORA)
);

-----BITACORA VA A REGISTRAR LOS EVENTOS QUE OCURRAN EN LA TABLA PRINCIPAL COMPUTADORA(TRIGGER)



CREATE TABLE BIT_COMPUTADORA(
ID_BIT NUMBER,
---VALORES DE CONTROL NEW Y OLD
MARCA NVARCHAR2 (100),
MODELO NVARCHAR2 (100),
PROCESADOR NVARCHAR2 (100),
RAM NUMBER,
PRECIO NUMBER,
MOVIMIENTO NVARCHAR2(100),
ID_COMPUTADORA NUMBER,
--

MARCA_OLD NVARCHAR2 (100),
MODELO_OLD NVARCHAR2(100),
PROCESADOR_OLD NVARCHAR2(100),
RAM_OLD NVARCHAR2(100),
PRECIO_OLD NVARCHAR2(100),
--CAMPOS DE CONTROL

FECHA_MOV DATE,
USUARIO NVARCHAR2(100),
CONSTRAINT BIT_COMPU_PK PRIMARY KEY(ID_BIT)
);


---TRIGGER ---> REGISTRA CUANDO UNA NUEVA CIMPUTADORA SE DA DE ALTA

CREATE OR REPLACE TRIGGER  TR_I_COMPUTADORA
AFTER INSERT ON COMPUTADORA
FOR EACH ROW
DECLARE
LV_ID_BIT NUMBER;
LV_FECHA DATE;
LV_USUARIO NVARCHAR2(100);

BEGIN 
--INICIALIZAR LAS VARIABLES PARA LOS REGISTROS DE NUEVAS COMPUTADORAS
SELECT USER INTO LV_USUARIO FROM DUAL;
SELECT SYSDATE INTO LV_FECHA FROM DUAL;
SELECT COUNT (ID_BIT) + 1 INTO LV_ID_BIT FROM BIT_COMPUTADORA;

---REGISTRAR LA NUEVA COMPUTADORA QUE SE AGREGA
INSERT INTO BIT_COMPUTADORA(ID_BIT, ID_COMPUTADORA, MARCA, MODELO, PROCESADOR, RAM, PRECIO, MARCA_OLD, MODELO_OLD, PROCESADOR_OLD, RAM_OLD, PRECIO_OLD, 
FECHA_MOV,USUARIO, MOVIMIENTO)
VALUES (LV_ID_BIT, : NEW.ID_COMPUTADORA, :NEW.MARCA, :NEW.MODELO, :NEW.PROCESADOR, :NEW.RAM, :NEW.PRECIO,NULL,NULL,NULL,0,0,
LV_FECHA, LV_USUARIO,'INSERT');

 END TR_I_COMPUTADORA;
/

---OBTENER EL USUARIO

SELECT USER FROM DUAL;


--BOTENER LA FECHA 

SELECT SYSDATE FROM DUAL;

ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MM-YYYY GH24:MI:SS';

SELECT COUNT (ID_BIT) + 1 FROM BIT_COMPUTADORA;
SELECT NVL(MAX(ID_BIT), 0) + 1 FROM BIT_COMPUTADORA;

SELECT * FROM COMPUTADORA;
SELECT * FROM BIT_COMPUTADORA;

INSERT INTO COMPUTADORA VALUES (1, 'LENOVO', 'NUEVO MODELO','INTEL I5',8,8800 );
COMMIT;
