-----EJECUTAR UNA TAREA EM ESPECIFICO, PUEDE RECIBIR PARAMETROS Y PUEDE RETORNAR VALORES.
/*
CREATE OR REPLACE TIPO_BLOQUE NOMBRE
VALOR DE RETORNO
IS
-- VARIABLES, CONSTANTES O CURSORES
BEGIN
--INSTRUCCIONES
END NOMBRE;
/
*/

--CREAR UNA FUNCION QUE VALIDE SI UN NUMERO ES PAR O IMPAR

CREATE OR REPLACE FUNCTION FN_NUMERO_PAR(P_NUMERO IN NUMBER)
RETURN NVARCHAR2
IS
LV_RESULTADO NVARCHAR2 (100);
BEGIN
-- VALIDAR SI EL PARAMETRO ES PAR
--FUNCION MOD ----> RESIDUO DE UNA DIVISON 8/4 = 2 r=0 
IF (MOD(P_NUMERO, 2) = 0) THEN 
LV_RESULTADO := 'EL NUMERO ' || P_NUMERO || ' ES PAR : ';
ELSE 
LV_RESULTADO := 'EL NUMERO ' || P_NUMERO || ' ES IMPAR.' ;
END IF ;
RETURN LV_RESULTADO;
END FN_NUMERO_PAR;
/


BEGIN DBMS_OUTPUT.PUT_LINE(FN_NUMERO_PAR(1567));
END;
/

SELECT FN_NUMERO_PAR(1200) AS PAR FROM DUAL;