---SEMANA 2 BASE DE DATOS----------->  ES UN CONJUNTO ORGANIZADO DE DATOS QUE SE ALMACENAN ELECTRONICAMENTE EN UN SISTEMA. SE PUEDE ACCEDER A ELLOS Y ADMINISTRARLOS 
---REGLAS DE NEGOCIO: SON RESTRICCIONES QUE SE APLICAN A LOS DATOS PARA GARANTIZAR INTEGRIDAD,CONSISTENCIA Y COHERENCIA.
----TIPOS DE BASE DE DATOS: RELACIONALES ---------> LOS DATOS SON ALMACENADOS EN TABLAS Y QUE PUEDE RELACIONARSE ADEMAS DE QUE 
---EL LENGUAJE UTILIZADO ES SQL ----------> Y NO RELACIONALES TAMBIEN LLAMADAS NO SQL ESTAN DISEÑADAS PARA ANEJAR GRANDES VALUMENES DE DATOS NO ESTRUCTURADOS O SEMI ESTRUCTURADOS.
-----SQL---> ES UN LENGUAJE PARA COMUNICARSE CON LA BASE DE DATOS,Y GESTIONAR ADEMAS DE MANIPULAR LOS DATOS EN NUESTRA BASE.
----- GESTOR DE BASE DE DATOS: ES UN SOFTWARE DISEÑADO PARA GESTIONAR Y ADMINISTRAR BASES DA DATOS
----> MYSQL, SQL SERVER , POTSCRES, ORACLE.

-----TABLAS O TAMBIEN ENTIDADES ES UNA ESTRUCTURA ORGANIZADA QUE ALMACENA DATOS EN FORMA TABULAR. (FILAS Y COLUMNAS)
----COLUMNAS O CAMPOS ES UNA UNIDAD BASICA DE DATOS QUE REPRESENTA UNA CARACTERISTICA O ATRIBUTO EN ESPESIFICO DE UNA ENTIDAD .
------CARDINALIDAD : 1:1, 1:N, N:1, N:M.
-----CONSTRAINS: RESTRICCIONES APLICADAS A LAS COLUMNAS PARA GARANTIZAR LA INTEGRIDAD DE LSO DATOS:PK, FK, U, NN, C.
-----1. DML (Data Manipulation Language / Lenguaje de Manipulación de Datos) Permite consultar y modificar los datos dentro de las tablas. Incluye comandos como: SELECT – Recuperar datos. INSERT – Insertar nuevos datos. UPDATE – Modificar datos existentes. DELETE – Eliminar datos.
----2. DDL (Data Definition Language / Lenguaje de Definición de Datos)Sirve para definir o modificar la estructura de la base de datos (tablas, índices, vistas, etc.).Incluye comandos como: CREATE – Crear objetos (tablas, vistas, etc.).ALTER – Modificar objetos.DROP – Eliminar objetos.3. DCL (Data Control Language / Lenguaje de Control de Datos)Permite gestionar los permisos y el acceso a los datos.Incluye comandos como:GRANT – Conceder permisos.REVOKE – Revocar permisos.

----NUMBER, NVARCHAT2,VARCHAR, FLOAT, INT, BOOLEAN, DATE.



---DDL
CREATE TABLE PERSONA(
ID_PERSONA NUMBER,
NOMBRE NVARCHAR2(100),
APELLIDOS NVARCHAR2(100),
EDAD NUMBER,
OCUPACION NVARCHAR2(100)
);

---DML

INSERT INTO PERSONA VALUES (1, 'OSCAR', 'ROMO', 29, 'ING EN SISTEMAS');

COMMIT; ---GUARDAR LA MODIFICACION EN LA BASE DE DATOS 
----LIBERA LA ENTIDAD PARA NUEVAS MODIFICACIONES 
---- LOS DATOS LOS VUELVE PERSISTENTES: LOS DATOS QUEDAN ALMACENADOS Y DISPONIBLES EN CUALQUIER MOMENTO EN QUE QUIERA ACCEDER A ELLOS.

---- PERMITE OBSERVAR LOS CAMBIOS REALIZADOS.


SELECT * FROM PERSONA;

INSERT INTO PERSONA VALUES (2, 'RJAS', 'ROMO', 18, 'ABOGADA');
INSERT INTO PERSONA VALUES (1, 'RJAS', 'ROMO', 18, 'ABOGADA');

---DDL
DROP TABLE PERSONA;


---AGREGANDO PK
CREATE TABLE PERSONA(
ID_PERSONA NUMBER,
NOMBRE NVARCHAR2(100),
APELLIDOS NVARCHAR2(100),
EDAD NUMBER,
OCUPACION NVARCHAR2(100),
CONSTRAINT PERSONA_PK PRIMARY KEY(ID_PERSONA)
);