---PROCEDIMIENTO ALMACENADO
SELECT * FROM COMPUTADORA;


---CREAR UNA TABLA PARA RESPALDAR LA INFORMACION ALMACENADA EN LA ENTIDAD COMPUTADORA}

CREATE TABLE COMPUTADORA_PRD(
ID_COMPUTADORA NUMBER,
MARCA NVARCHAR2(100),
MODELO NVARCHAR2(100),
PROCESADOR NVARCHAR2(100),
RAM NUMBER,
PRECIO NUMBER,
CONSTRAINT COMPU_PRD_PK PRIMARY KEY(ID_COMPUTADORA)
);

--SINTAXIS DEL PROCEDIMIENTO ALMACENADO
/*
CREATE OR REPLACE TIPO NOMBRE
IS
---- VARIABLES,CONSTANTE Y CURSORES
BEGIN 
--INSTRUCCIONES
END NOMBRE;
/
*/



---RESPALDAR LA INFORMACION 
CREATE OR REPLACE PROCEDURE PR_RESPALDAR

IS 
BEGIN 
---BORRAR EL CONTENIDO DE LA TABLA DE RESPALDO 

DELETE FROM COMPUTADORA_PRD;

---REALIZAR EL RESPALDO

INSERT INTO COMPUTADORA_PRD(ID_COMPUTADORA, MARCA, MODELO, PROCESADOR, RAM, PRECIO)
SELECT ID_COMPUTADORA, MARCA, MODELO, PROCESADOR, RAM, PRECIO FROM COMPUTADORA;
END PR_RESPALDAR;
/

INSERT INTO COMPUTADORA VALUES(6, 'HP', 'DESKTOP', 'AMD 5', 12, 9900);
INSERT INTO COMPUTADORA VALUES(7, 'Dell', 'Inspiron 14', 'AMD Ryzen 5', 16, 15500);
INSERT INTO COMPUTADORA VALUES(8, 'LENOVO', '2025', 'INTEL  I5', 12, 10900);



SELECT * FROM COMPUTADORA;
SELECT * FROM COMPUTADORA_PRD;
EXECUTE PR_RESPALDAR;

INSERT INTO COMPUTADORA VALUES(9, 'ARMANDO', '2025', 'INTEL  I5', 12, 10900);