SELECT * FROM PERSONA;
INSERT INTO PERSONA VALUES (3, 'GUILLERMO', 'ROMO', 29, 'ING_SISTEMAS');
INSERT INTO PERSONA VALUES (4, 'LAURA', 'MARTÍNEZ', 34, 'ARQUITECTA');
INSERT INTO PERSONA VALUES(5,'RAUL','MARTINEZ',28,'AGRONOMO');
INSERT INTO PERSONA VALUES(6,'EMILIA','JIMENEZ',32,'CONTADORA');
INSERT INTO PERSONA VALUES (7, 'ELIAM', 'ROMO', 25, 'ING_SISTEMAS');
INSERT INTO PERSONA VALUES (8, 'PERLA', 'MARTÍNEZ', 23, 'ABOGADA');

--MODIFICAR EL NOMBRE DE UN CAMPO

ALTER TABLE PERSONA RENAME COLUMN OCUPACION TO PROFESION;

-----MODIFICAR EL VALRO DE UN CAMPO 

UPDATE PERSONA SET PREFESION = 'ING. SISTEMAS' WHERE ID_PERSONA = 7;

--ORDER BY
SELECT * FROM PERSONA ORDER BY EDAD DESC;
SELECT * FROM PERSONA ORDER BY EDAD ASC;

-----BUSCAR POR CARACTERES 
----APELLIDO QUE CONTENGA UNA M

SELECT * FROM PERSONA WHERE APELLIDO LIKE 'M%';
SELECT * FROM PERSONA WHERE APELLIDO LIKE '%O%';
SELECT * FROM PERSONA WHERE APELLIDO LIKE '%Z';

--UTLIZAR TABLA AUXILIAR : DUAL, RENOMBRAR COLIMNAS U OPERACION CON LA PALABRA AS
SELECT 5 + 5 AS SUMA FROM DUAL;

--LENGHT

SELECT LENGTH('ESTA ES UNA CADENA PARA EL USO DE LENGHT') AS TAMANIO FROM DUAL;

INSERT INTO PERSONA VALUES (9, 'SILVIA', 'MORA', 33, NULL);
--- LAS PERSONAS QUE EN PROFESION NO TENGAN NULL

SELECT * FROM PERSONA WHERE PROFESION IS NOT NULL;


----RANGOS NUMERICOS
----PERSONA MAYORES A 25

SELECT * FROM PERSONA WHERE EDAD > 25;

----PERSONA ENTRE 22 Y 30 
SELECT * FROM PERSONA WHERE EDAD > 22 AND EDAD <30;
SELECT * FROM PERSONA WHERE EDAD BETWEEN 22 AND 30;



----BUSCAR POR ID 

SELECT * FROM PERSONA WHERE ID_PERSONA = 1 OR ID_PERSONA = 2 OR ID_PERSONA =8;
---IN
SELECT * FROM PERSONA WHERE ID_PERSONA IN (1,2,8,9);


----GROUP BY 

SELECT PROFESION FROM PERSONA GROUP BY PROFESION;

----COUNT 

SELECT COUNT (ID_PERSONA ) AS CANTIDAD FROM PERSONA WHERE EDAD > 30;
