---LOS PAQUETES SE DIVIDEN EN HEADER Y BODY
--- HEADER

CREATE OR REPLACE PACKAGE PKG_GENERAL

AS 

---FUNCION 

FUNCTION FN_NUMERO_PAR(P_NUMERO IN NUMBER)RETURN NVARCHAR2;


---PROCEDIMIENTO 
PROCEDURE PR_DETALLE_LIBRO;
END PKG_GENERAL;
/
---BODY 

CREATE OR REPLACE PACKAGE BODY PKG_GENERAL
AS 

--FUNCION 


FUNCTION FN_NUMERO_PAR(P_NUMERO IN NUMBER)
RETURN NVARCHAR2
IS
LV_RESULTADO NVARCHAR2 (100);
BEGIN
-- VALIDAR SI EL PARAMETRO ES PAR
--FUNCION MOD ----> RESIDUO DE UNA DIVISON 8/4 = 2 r=0 
IF (MOD(P_NUMERO, 2) = 0) THEN 
LV_RESULTADO := 'EL NUMERO ' || P_NUMERO || ' ES PAR : ';
ELSE 
LV_RESULTADO := 'EL NUMERO ' || P_NUMERO || ' ES IMPAR.';
END IF ;
RETURN LV_RESULTADO;
END FN_NUMERO_PAR;

---PROCEDIMIENTO 
PROCEDURE PR_DETALLE_LIBRO

IS 
--- DECLARAMOS EL CURSOR 


CURSOR LIBRO_INFO IS 
SELECT NOMBRE,
CASE GENERO
    WHEN 1 THEN 'DRAMA'
    WHEN 2 THEN 'TERROR'
    WHEN 3 THEN 'HISTORIA'
    WHEN 4 THEN 'CIENCIA FICCION'
    WHEN 5 THEN 'POESIA'
    ELSE 'SIN GENERO'
    
    END AS GENERO_LIBRO, PRECIO 
    FROM LIBRO;
    ---VARIABLE LOCALES 
    
    LV_NOMBRE NVARCHAR2(100);
    LV_GENERO NVARCHAR2(100);
    LV_PRECIO LIBRO.PRECIO%TYPE; ---- % ES LO MISMO QUE NUMBER, SIRVE PARA REFERECNIAR EN CAS ODE NO SABER QUE TIPO ES NUMBER, NVARCHAR2 ETC
    
    BEGIN 
    ---ABRIR EL CURSOR 
    
    OPEN LIBRO_INFO;
    
    ---RECUPERO LOS DATOS DEL CURSOR 
    
    LOOP
    --ALMACENARLO EN LAS VARIABLES LOCALES
    
    FETCH LIBRO_INFO INTO LV_NOMBRE, LV_GENERO, LV_PRECIO;
    
    --CONDICION PARA CERRAR EL CICLO
    
    EXIT WHEN LIBRO_INFO%NOTFOUND;
    
    ----MOSTRAR EN LA CONSOLA LO QUE TIENEN LAS VARIABLES 
    
    
    DBMS_OUTPUT.PUT_LINE('LIBRO: ' || LV_NOMBRE || ' DEL GENERO ' || LV_GENERO || ' CUESTA $' || LV_PRECIO);
    END LOOP;
    
    ---CIERRO EL CURSOR 
    
    
    CLOSE LIBRO_INFO;
    
    
    END PR_DETALLE_LIBRO;
    



END PKG_GENERAL;
/

  





