CREATE TABLE CARRERA_WS (
  ID_CARRERA        NUMBER PRIMARY KEY,
  NOMBRE            NVARCHAR2(100),
  DURACION          NUMBER,
  MODALIDAD         NVARCHAR2(50),
  NIVEL_ACADEMICO   NVARCHAR2(50)
);

CREATE TABLE ALUMNO_WS (
  ID_ALUMNO    NUMBER PRIMARY KEY,
  NOMBRE       NVARCHAR2(100),
  APELLIDO     NVARCHAR2(100),
  EDAD         NUMBER,
  CARRERA_ID   NUMBER,
  CONSTRAINT FK_ALUMNO_CARRERA_WS FOREIGN KEY (CARRERA_ID) REFERENCES CARRERA_WS(ID_CARRERA)
);


INSERT INTO CARRERA_WS (ID_CARRERA, NOMBRE, DURACION, MODALIDAD, NIVEL_ACADEMICO) VALUES (1, 'Ingeniería en Sistemas', 8, 'Escolarizado', 'Licenciatura');
INSERT INTO CARRERA_WS (ID_CARRERA, NOMBRE, DURACION, MODALIDAD, NIVEL_ACADEMICO) VALUES (2, 'Administración de Empresas', 7, 'En línea', 'Licenciatura');
INSERT INTO CARRERA_WS (ID_CARRERA, NOMBRE, DURACION, MODALIDAD, NIVEL_ACADEMICO) VALUES (3, 'Medicina', 12, 'Escolarizado', 'Licenciatura');
INSERT INTO CARRERA_WS (ID_CARRERA, NOMBRE, DURACION, MODALIDAD, NIVEL_ACADEMICO) VALUES (4, 'Arquitectura', 9, 'Presencial', 'Licenciatura');
INSERT INTO CARRERA_WS (ID_CARRERA, NOMBRE, DURACION, MODALIDAD, NIVEL_ACADEMICO) VALUES (5, 'Derecho', 8, 'Escolarizado', 'Licenciatura');



INSERT INTO ALUMNO_WS (ID_ALUMNO, NOMBRE, APELLIDO, EDAD, CARRERA_ID) VALUES (1, 'Juan', 'Pérez', 21, 1);
INSERT INTO ALUMNO_WS (ID_ALUMNO, NOMBRE, APELLIDO, EDAD, CARRERA_ID) VALUES (2, 'María', 'Gómez', 22, 2);
INSERT INTO ALUMNO_WS (ID_ALUMNO, NOMBRE, APELLIDO, EDAD, CARRERA_ID) VALUES (3, 'Carlos', 'Ramírez', 23, 3);
INSERT INTO ALUMNO_WS (ID_ALUMNO, NOMBRE, APELLIDO, EDAD, CARRERA_ID) VALUES (4, 'Lucía', 'Fernández', 20, 1);
INSERT INTO ALUMNO_WS (ID_ALUMNO, NOMBRE, APELLIDO, EDAD, CARRERA_ID) VALUES (5, 'Ana', 'Martínez', 24, 5);

COMMIT;


SELECT * FROM CARRERA_WS;

SELECT * FROM ALUMNO_WS;